#!/usr/bin/env python3
"""
Translate Italian vocabulary entries that have 'Translation needed' as their English value.
This script provides English translations for CEFR vocabulary (A1, A2, B1, B2).
"""

import sqlite3
import json
from pathlib import Path

# Database path
DB_PATH = Path(__file__).parent.parent / 'data' / 'curriculum.db'

# Italian to English translations dictionary
# Organized by word type for clarity
TRANSLATIONS = {
    # Common words and prepositions
    'a': 'to, at',
    'di': 'of, from',
    'in': 'in, to',
    'da': 'from, by, since',
    'con': 'with',
    'su': 'on, about',
    'per': 'for, through',
    'tra': 'between, among',
    'fra': 'between, among',

    # Verbs (infinitive forms)
    'amare': 'to love',
    'aprire': 'to open',
    'arrivare': 'to arrive',
    'ascoltare': 'to listen',
    'aspettare': 'to wait',
    'avere': 'to have',
    'bastare': 'to be enough',
    'bere': 'to drink',
    'cadere': 'to fall',
    'cambiare': 'to change',
    'camminare': 'to walk',
    'cantare': 'to sing',
    'capire': 'to understand',
    'cercare': 'to look for, to search',
    'chiamare': 'to call',
    'chiudere': 'to close',
    'cominciare': 'to begin',
    'comprare': 'to buy',
    'conoscere': 'to know (a person/place)',
    'correre': 'to run',
    'costare': 'to cost',
    'credere': 'to believe',
    'cucinare': 'to cook',
    'dare': 'to give',
    'decidere': 'to decide',
    'dimenticare': 'to forget',
    'dire': 'to say, to tell',
    'diventare': 'to become',
    'domandare': 'to ask',
    'dormire': 'to sleep',
    'dovere': 'to have to, must',
    'entrare': 'to enter',
    'essere': 'to be',
    'fare': 'to do, to make',
    'fermare': 'to stop',
    'finire': 'to finish',
    'giocare': 'to play',
    'guardare': 'to watch, to look at',
    'guidare': 'to drive',
    'imparare': 'to learn',
    'incontrare': 'to meet',
    'insegnare': 'to teach',
    'lavorare': 'to work',
    'leggere': 'to read',
    'mandare': 'to send',
    'mangiare': 'to eat',
    'mettere': 'to put',
    'morire': 'to die',
    'mostrare': 'to show',
    'nascere': 'to be born',
    'offrire': 'to offer',
    'pagare': 'to pay',
    'parlare': 'to speak',
    'partire': 'to leave, to depart',
    'passare': 'to pass, to spend (time)',
    'pensare': 'to think',
    'perdere': 'to lose',
    'piacere': 'to please, to like',
    'piangere': 'to cry',
    'portare': 'to bring, to carry, to wear',
    'potere': 'to be able to, can',
    'prendere': 'to take',
    'preferire': 'to prefer',
    'preparare': 'to prepare',
    'presentare': 'to present, to introduce',
    'provare': 'to try',
    'pulire': 'to clean',
    'restare': 'to stay, to remain',
    'ricevere': 'to receive',
    'ricordare': 'to remember',
    'ridere': 'to laugh',
    'rimanere': 'to remain, to stay',
    'ripetere': 'to repeat',
    'riposare': 'to rest',
    'rispondere': 'to answer',
    'ritornare': 'to return',
    'rompere': 'to break',
    'salire': 'to go up, to climb',
    'salutare': 'to greet',
    'sapere': 'to know (a fact)',
    'sbagliare': 'to make a mistake',
    'scendere': 'to go down, to get off',
    'scegliere': 'to choose',
    'scrivere': 'to write',
    'scusare': 'to excuse',
    'seguire': 'to follow',
    'sembrare': 'to seem',
    'sentire': 'to hear, to feel',
    'servire': 'to serve',
    'smettere': 'to stop, to quit',
    'spedire': 'to send, to mail',
    'spendere': 'to spend (money)',
    'sperare': 'to hope',
    'spiegare': 'to explain',
    'stare': 'to stay, to be',
    'studiare': 'to study',
    'suonare': 'to play (instrument), to ring',
    'svegliare': 'to wake up',
    'telefonare': 'to phone',
    'tenere': 'to hold, to keep',
    'tornare': 'to return',
    'trovare': 'to find',
    'uscire': 'to go out',
    'vedere': 'to see',
    'vendere': 'to sell',
    'venire': 'to come',
    'vestire': 'to dress',
    'viaggiare': 'to travel',
    'vincere': 'to win',
    'visitare': 'to visit',
    'vivere': 'to live',
    'volere': 'to want',

    # Nouns
    'aceto': 'vinegar',
    'aereo': 'airplane',
    'affetto': 'affection',
    'agenzia': 'agency',
    'albero': 'tree',
    'alfabeto': 'alphabet',
    'ambasciata': 'embassy',
    'amico': 'friend',
    'amore': 'love',
    'animale': 'animal',
    'appartamento': 'apartment',
    'appuntamento': 'appointment',
    'arte': 'art',
    'autobus': 'bus',
    'automobile': 'car',
    'autunno': 'autumn, fall',
    'avvocato': 'lawyer',
    'bagno': 'bathroom',
    'bambino': 'child',
    'banca': 'bank',
    'bar': 'bar, café',
    'bicicletta': 'bicycle',
    'biglietto': 'ticket',
    'borsa': 'bag, purse',
    'bottiglia': 'bottle',
    'braccio': 'arm',
    'caldo': 'heat, warmth',
    'camera': 'room',
    'cameriere': 'waiter',
    'camicia': 'shirt',
    'campagna': 'countryside',
    'cane': 'dog',
    'canzone': 'song',
    'cappello': 'hat',
    'cappotto': 'coat',
    'carne': 'meat',
    'carta': 'paper',
    'casa': 'house, home',
    'cassiere': 'cashier',
    'centro': 'center',
    'ciao': 'hello, goodbye',
    'cielo': 'sky',
    'cinema': 'cinema, movie theater',
    'cintura': 'belt',
    'città': 'city',
    'classe': 'class',
    'cliente': 'client, customer',
    'colazione': 'breakfast',
    'collega': 'colleague',
    'collo': 'neck',
    'colore': 'color',
    'coltello': 'knife',
    'compleanno': 'birthday',
    'computer': 'computer',
    'conoscenza': 'knowledge, acquaintance',
    'consiglio': 'advice',
    'conto': 'bill, account',
    'conversazione': 'conversation',
    'coperta': 'blanket',
    'corpo': 'body',
    'corridoio': 'corridor, hallway',
    'corso': 'course',
    'cortile': 'courtyard',
    'cosa': 'thing',
    'costume': 'costume, swimsuit',
    'cotone': 'cotton',
    'cravatta': 'tie',
    'cucchiaio': 'spoon',
    'cucina': 'kitchen',
    'cugino': 'cousin',
    'cuore': 'heart',
    'dente': 'tooth',
    'denaro': 'money',
    'destra': 'right',
    'dito': 'finger',
    'documento': 'document',
    'dolce': 'dessert, sweet',
    'domanda': 'question',
    'donna': 'woman',
    'dottore': 'doctor',
    'dubbio': 'doubt',
    'edificio': 'building',
    'entrata': 'entrance',
    'errore': 'error, mistake',
    'esempio': 'example',
    'esperienza': 'experience',
    'estate': 'summer',
    'età': 'age',
    'euro': 'euro',
    'fabbrica': 'factory',
    'faccia': 'face',
    'fame': 'hunger',
    'famiglia': 'family',
    'farmacia': 'pharmacy',
    'favore': 'favor',
    'felicità': 'happiness',
    'fermata': 'stop (bus/tram)',
    'festa': 'party, holiday',
    'figlia': 'daughter',
    'figlio': 'son',
    'film': 'movie, film',
    'fine': 'end',
    'finestra': 'window',
    'fiore': 'flower',
    'firma': 'signature',
    'foglia': 'leaf',
    'foglio': 'sheet (of paper)',
    'fontana': 'fountain',
    'forchetta': 'fork',
    'formaggio': 'cheese',
    'forno': 'oven',
    'foto': 'photo',
    'fotografia': 'photograph',
    'francese': 'French',
    'fratello': 'brother',
    'freddo': 'cold',
    'fretta': 'hurry',
    'frigorifero': 'refrigerator',
    'frutta': 'fruit',
    'fuoco': 'fire',
    'gabinetto': 'toilet',
    'gamba': 'leg',
    'gatto': 'cat',
    'gelato': 'ice cream',
    'gente': 'people',
    'genitore': 'parent',
    'giacca': 'jacket',
    'giardino': 'garden',
    'ginocchio': 'knee',
    'giornale': 'newspaper',
    'giornata': 'day (duration)',
    'giorno': 'day',
    'giovane': 'young person',
    'gioventù': 'youth',
    'gita': 'trip, excursion',
    'gonna': 'skirt',
    'governo': 'government',
    'gradino': 'step',
    'grado': 'degree',
    'grido': 'shout, cry',
    'gruppo': 'group',
    'guanto': 'glove',
    'guerra': 'war',
    'gusto': 'taste',
    'idea': 'idea',
    'impiegato': 'employee, clerk',
    'impresa': 'enterprise, company',
    'incidente': 'accident',
    'incontro': 'meeting, encounter',
    'indirizzo': 'address',
    'infanzia': 'childhood',
    'infermiere': 'nurse',
    'informazione': 'information',
    'ingegnere': 'engineer',
    'inglese': 'English',
    'ingresso': 'entrance',
    'insalata': 'salad',
    'insegnante': 'teacher',
    'interesse': 'interest',
    'interno': 'interior',
    'inverno': 'winter',
    'invito': 'invitation',
    'isola': 'island',
    'italiano': 'Italian',
    'lago': 'lake',
    'lampada': 'lamp',
    'lana': 'wool',
    'latte': 'milk',
    'lato': 'side',
    'lavoro': 'work, job',
    'legge': 'law',
    'legno': 'wood',
    'lettera': 'letter',
    'letto': 'bed',
    'lettura': 'reading',
    'lezione': 'lesson',
    'libertà': 'freedom',
    'libreria': 'bookstore, bookshelf',
    'libro': 'book',
    'lì': 'there',
    'lingua': 'language, tongue',
    'lino': 'linen',
    'lira': 'lira (currency)',
    'lista': 'list',
    'locale': 'room, place',
    'luna': 'moon',
    'lunedì': 'Monday',
    'luogo': 'place',
    'luce': 'light',
    'macchina': 'car, machine',
    'madre': 'mother',
    'maestra': 'elementary teacher',
    'magazzino': 'warehouse, department store',
    'maggio': 'May',
    'maglietta': 'T-shirt',
    'maglione': 'sweater',
    'male': 'evil, pain',
    'mamma': 'mom',
    'mancanza': 'lack',
    'mano': 'hand',
    'manzo': 'beef',
    'mare': 'sea',
    'marito': 'husband',
    'martedì': 'Tuesday',
    'marzo': 'March',
    'materiale': 'material',
    'materia': 'subject, matter',
    'matita': 'pencil',
    'matrimonio': 'marriage, wedding',
    'mattina': 'morning',
    'medico': 'doctor',
    'mela': 'apple',
    'memoria': 'memory',
    'meno': 'less',
    'mensa': 'cafeteria',
    'mente': 'mind',
    'menù': 'menu',
    'mercato': 'market',
    'mercoledì': 'Wednesday',
    'mese': 'month',
    'mestiere': 'trade, occupation',
    'metà': 'half',
    'metro': 'meter, subway',
    'mezzanotte': 'midnight',
    'mezzo': 'means, half',
    'mezzogiorno': 'noon, midday',
    'miglio': 'mile',
    'minestra': 'soup',
    'minuto': 'minute',
    'misura': 'measure, size',
    'mobile': 'piece of furniture',
    'moda': 'fashion',
    'modello': 'model',
    'modo': 'way, manner',
    'moglie': 'wife',
    'momento': 'moment',
    'mondo': 'world',
    'montagna': 'mountain',
    'monumento': 'monument',
    'morte': 'death',
    'mostra': 'exhibition',
    'motivo': 'reason, motive',
    'moto': 'motorcycle',
    'motore': 'motor, engine',
    'movimento': 'movement',
    'mucca': 'cow',
    'muro': 'wall',
    'museo': 'museum',
    'musica': 'music',
    'nascita': 'birth',
    'naso': 'nose',
    'natura': 'nature',
    'nave': 'ship',
    'nazione': 'nation',
    'nebbia': 'fog',
    'negozio': 'shop, store',
    'nemico': 'enemy',
    'nero': 'black',
    'neve': 'snow',
    'nido': 'nest',
    'nipote': 'nephew, niece, grandchild',
    'nome': 'name',
    'nonno': 'grandfather',
    'nord': 'north',
    'notizia': 'news',
    'notte': 'night',
    'novità': 'novelty, news',
    'nozze': 'wedding',
    'numero': 'number',
    'nuora': 'daughter-in-law',
    'nuoto': 'swimming',
    'nuvola': 'cloud',

    # Adverbs
    'adesso': 'now',
    'ancora': 'still, yet, again',
    'anzi': 'on the contrary, rather',
    'appena': 'just, barely',
    'appunto': 'exactly, precisely',
    'assai': 'very much, a lot',
    'attraverso': 'through, across',
    'avanti': 'forward, ahead',
    'bene': 'well',
    'certamente': 'certainly',
    'certo': 'certainly',
    'circa': 'about, approximately',
    'come': 'how, as, like',
    'completamente': 'completely',
    'comunque': 'however, anyway',
    'contro': 'against',
    'così': 'so, thus',
    'davanti': 'in front',
    'davvero': 'really',
    'dentro': 'inside',
    'dietro': 'behind',
    'direttamente': 'directly',
    'dopo': 'after, later',
    'dove': 'where',
    'dovunque': 'wherever',
    'dunque': 'therefore, so',
    'durante': 'during',
    'ecco': 'here is, there is',
    'esattamente': 'exactly',
    'facilmente': 'easily',
    'finalmente': 'finally',
    'fino': 'until, up to',
    'forse': 'maybe, perhaps',
    'forte': 'strongly, loudly',
    'fuori': 'outside',
    'generalmente': 'generally',
    'già': 'already',
    'giù': 'down',
    'insieme': 'together',
    'invece': 'instead',
    'là': 'there',
    'laggiù': 'down there',
    'lassù': 'up there',
    'lontano': 'far',
    'lì': 'there',
    'male': 'badly',
    'mai': 'never, ever',
    'meglio': 'better',
    'mentre': 'while',
    'molto': 'very, much',
    'nemmeno': 'not even',
    'neanche': 'not even',
    'neppure': 'not even',
    'niente': 'nothing',
    'normalmente': 'normally',
    'oggi': 'today',
    'ogni': 'every',
    'ognuno': 'everyone',
    'oltre': 'beyond, besides',
    'oppure': 'or',
    'ora': 'now',
    'ormai': 'by now',
    'ovunque': 'everywhere',
    'parecchio': 'quite a lot',
    'peggio': 'worse',
    'per esempio': 'for example',
    'perché': 'why, because',
    'perciò': 'therefore',
    'perfettamente': 'perfectly',
    'perfino': 'even',
    'però': 'however, but',
    'personalmente': 'personally',
    'più': 'more',
    'piuttosto': 'rather',
    'poco': 'little, not much',
    'poi': 'then, later',
    'presto': 'soon, early',
    'prima': 'before, first',
    'probabilmente': 'probably',
    'proprio': 'really, exactly',
    'purtroppo': 'unfortunately',
    'qua': 'here',
    'qualche': 'some',
    'qualcosa': 'something',
    'qualcuno': 'someone',
    'quando': 'when',
    'quanto': 'how much',
    'quasi': 'almost',
    'quindi': 'therefore, so',
    'rapidamente': 'rapidly',
    'raramente': 'rarely',
    'recentemente': 'recently',
    'sempre': 'always',
    'semplice': 'simple',
    'semplicemente': 'simply',
    'senza': 'without',
    'sicuramente': 'surely, certainly',
    'solamente': 'only',
    'solo': 'only, alone',
    'soprattutto': 'above all, especially',
    'sopra': 'above, on',
    'sotto': 'under, below',
    'specialmente': 'especially',
    'spesso': 'often',
    'stamattina': 'this morning',
    'stasera': 'this evening, tonight',
    'stamani': 'this morning',
    'stanotte': 'tonight, last night',
    'subito': 'immediately',
    'su': 'up',
    'tardi': 'late',
    'tanto': 'so much',
    'troppo': 'too much',
    'tuttavia': 'however',
    'tutto': 'all, everything',
    'ugualmente': 'equally',
    'ultimamente': 'lately',
    'veramente': 'really, truly',
    'verso': 'toward',
    'via': 'away',
    'vicino': 'near, close',
    'volentieri': 'willingly, gladly',

    # Adjectives
    'alto': 'tall, high',
    'altro': 'other',
    'ampio': 'wide, ample',
    'antico': 'ancient, old',
    'aperto': 'open',
    'azzurro': 'blue, azure',
    'basso': 'low, short',
    'bello': 'beautiful',
    'bianco': 'white',
    'blu': 'blue',
    'bravo': 'good, clever',
    'breve': 'brief, short',
    'brutto': 'ugly',
    'buono': 'good',
    'caldo': 'hot, warm',
    'calmo': 'calm',
    'caro': 'dear, expensive',
    'cattivo': 'bad, evil',
    'centrale': 'central',
    'certo': 'certain',
    'chiaro': 'clear, light',
    'chiuso': 'closed',
    'completo': 'complete',
    'comune': 'common',
    'contento': 'happy, content',
    'corto': 'short',
    'debole': 'weak',
    'destro': 'right',
    'difficile': 'difficult',
    'diretto': 'direct',
    'diverso': 'different',
    'dolce': 'sweet',
    'duro': 'hard',
    'economico': 'economic, cheap',
    'enorme': 'enormous',
    'estero': 'foreign',
    'facile': 'easy',
    'falso': 'false',
    'famoso': 'famous',
    'felice': 'happy',
    'fermo': 'still, stationary',
    'forte': 'strong',
    'fresco': 'fresh, cool',
    'freddo': 'cold',
    'gentile': 'kind, polite',
    'giovane': 'young',
    'giusto': 'right, correct',
    'grande': 'big, large, great',
    'grasso': 'fat',
    'grave': 'serious, grave',
    'grigio': 'grey',
    'grosso': 'big, thick',
    'importante': 'important',
    'impossibile': 'impossible',
    'intero': 'entire, whole',
    'interessante': 'interesting',
    'internazionale': 'international',
    'italiano': 'Italian',
    'largo': 'wide',
    'leggero': 'light (weight)',
    'lento': 'slow',
    'libero': 'free',
    'lungo': 'long',
    'maggiore': 'greater, older',
    'magro': 'thin, lean',
    'malato': 'sick, ill',
    'marito': 'married',
    'maturo': 'mature, ripe',
    'medio': 'average, medium',
    'migliore': 'better, best',
    'minore': 'smaller, younger',
    'moderno': 'modern',
    'molle': 'soft',
    'morto': 'dead',
    'nazionale': 'national',
    'naturale': 'natural',
    'necessario': 'necessary',
    'nero': 'black',
    'nobile': 'noble',
    'normale': 'normal',
    'notevole': 'notable, remarkable',
    'nuovo': 'new',
    'numeroso': 'numerous',
    'occidentale': 'western',
    'occupato': 'busy, occupied',
    'opportuno': 'opportune, appropriate',
    'ordinario': 'ordinary',
    'orientale': 'eastern',
    'oscuro': 'dark, obscure',
    'ottimo': 'excellent',
    'ovvio': 'obvious',
    'pari': 'equal, even',
    'particolare': 'particular',
    'passato': 'past',
    'paziente': 'patient',
    'peggiore': 'worse, worst',
    'perfetto': 'perfect',
    'pericoloso': 'dangerous',
    'personale': 'personal',
    'pesante': 'heavy',
    'piccolo': 'small',
    'pieno': 'full',
    'pigro': 'lazy',
    'politico': 'political',
    'popolato': 'populated',
    'popolare': 'popular',
    'possibile': 'possible',
    'povero': 'poor',
    'pratico': 'practical',
    'preciso': 'precise',
    'preferito': 'favorite',
    'presente': 'present',
    'presto': 'early, quick',
    'prezioso': 'precious',
    'primo': 'first',
    'principale': 'main, principal',
    'privato': 'private',
    'probabile': 'probable',
    'profondo': 'deep',
    'prossimo': 'next',
    'pubblico': 'public',
    'pulito': 'clean',
    'puro': 'pure',
    'quale': 'which',
    'qualsiasi': 'any, whatever',
    'qualunque': 'any, whatever',
    'quanto': 'how much',
    'quarto': 'fourth',
    'quello': 'that',
    'questo': 'this',
    'quieto': 'quiet',
    'quinto': 'fifth',
    'rapido': 'rapid, fast',
    'raro': 'rare',
    'recente': 'recent',
    'regionale': 'regional',
    'regolare': 'regular',
    'religioso': 'religious',
    'ricco': 'rich',
    'ridotto': 'reduced',
    'riservato': 'reserved',
    'romano': 'Roman',
    'rosso': 'red',
    'rotondo': 'round',
    'russo': 'Russian',
    'sacro': 'sacred',
    'salato': 'salty',
    'sano': 'healthy',
    'santo': 'saint, holy',
    'sbagliato': 'wrong, mistaken',
    'scarso': 'scarce',
    'scemo': 'stupid',
    'sciocco': 'foolish',
    'scomodo': 'uncomfortable',
    'sconosciuto': 'unknown',
    'scoperto': 'discovered, uncovered',
    'scorso': 'last, past',
    'scritto': 'written',
    'scuro': 'dark',
    'secco': 'dry',
    'secondo': 'second',
    'segreto': 'secret',
    'semplice': 'simple',
    'sensibile': 'sensitive',
    'serio': 'serious',
    'sereno': 'serene, clear',
    'severo': 'severe, strict',
    'sicuro': 'sure, safe',
    'significativo': 'significant',
    'simile': 'similar',
    'simpatico': 'nice, likeable',
    'sincero': 'sincere',
    'singolo': 'single',
    'sinistro': 'left',
    'sociale': 'social',
    'sodo': 'hard, firm',
    'solo': 'alone, only',
    'solito': 'usual',
    'sordo': 'deaf',
    'sorpreso': 'surprised',
    'sottile': 'thin, subtle',
    'spagnolo': 'Spanish',
    'speciale': 'special',
    'specifico': 'specific',
    'sporco': 'dirty',
    'stanco': 'tired',
    'strano': 'strange',
    'stretto': 'narrow, tight',
    'stupido': 'stupid',
    'successivo': 'successive, next',
    'sufficiente': 'sufficient',
    'superiore': 'superior, upper',
    'supremo': 'supreme',
    'sveglio': 'awake, alert',
    'tale': 'such',
    'tanto': 'so much',
    'tardo': 'late',
    'tedesco': 'German',
    'tenero': 'tender',
    'terribile': 'terrible',
    'terzo': 'third',
    'tipico': 'typical',
    'totale': 'total',
    'tranquillo': 'calm, quiet',
    'triste': 'sad',
    'troppo': 'too much',
    'ultimo': 'last',
    'uguale': 'equal',
    'unico': 'unique, only',
    'unito': 'united',
    'universale': 'universal',
    'umano': 'human',
    'umido': 'humid, damp',
    'urgente': 'urgent',
    'usato': 'used',
    'utile': 'useful',
    'vario': 'various',
    'vasto': 'vast',
    'vecchio': 'old',
    'veloce': 'fast',
    'vero': 'true',
    'verde': 'green',
    'vergine': 'virgin',
    'vicino': 'near',
    'vigile': 'vigilant',
    'vile': 'vile, cowardly',
    'vivo': 'alive, living',
    'vocale': 'vocal',
    'vuoto': 'empty',

    # Conjunctions
    'anche': 'also, too',
    'che': 'that, which, who',
    'dunque': 'therefore',
    'e': 'and',
    'ma': 'but',
    'mentre': 'while',
    'o': 'or',
    'oppure': 'or',
    'perché': 'because, why',
    'però': 'however, but',
    'quando': 'when',
    'quindi': 'therefore',
    'se': 'if',
    'sia': 'both, whether',

    # Interjections
    'aiuto': 'help',
    'arrivederci': 'goodbye',
    'attenzione': 'attention',
    'auguri': 'best wishes',
    'basta': 'enough',
    'bene': 'well, good',
    'bravo': 'well done',
    'buongiorno': 'good morning, hello',
    'buonasera': 'good evening',
    'buonanotte': 'good night',
    'ciao': 'hi, bye',
    'congratulazioni': 'congratulations',
    'ecco': 'here is',
    'grazie': 'thank you',
    'prego': 'you\'re welcome, please',
    'salve': 'hello',
    'scusa': 'sorry, excuse me',
    'scusi': 'excuse me (formal)',
    'sì': 'yes',
    'no': 'no',
    'va bene': 'okay',

    # Pronouns
    'chi': 'who',
    'ci': 'us, there',
    'io': 'I',
    'lei': 'she, you (formal)',
    'loro': 'they, them',
    'lui': 'he',
    'me': 'me',
    'mi': 'me, myself',
    'noi': 'we',
    'qualcuno': 'someone',
    'qualcosa': 'something',
    'se': 'oneself',
    'si': 'oneself, one',
    'te': 'you',
    'ti': 'you, yourself',
    'tu': 'you',
    'voi': 'you (plural)',
}


def translate_word(italian: str, word_type: str = None) -> str:
    """
    Translate an Italian word to English.
    Returns the translation if found, otherwise returns the original word.
    """
    # Clean the Italian word (remove articles)
    clean = italian.lower().strip()

    # Remove common articles
    for article in ['il ', 'lo ', 'la ', "l'", 'i ', 'gli ', 'le ', 'un ', 'uno ', 'una ', "un'"]:
        if clean.startswith(article):
            clean = clean[len(article):]
            break

    # Look up in dictionary
    if clean in TRANSLATIONS:
        return TRANSLATIONS[clean]

    # If not found, return indication that manual translation is needed
    return f"NEEDS_MANUAL: {italian}"


def main():
    """Main function to translate vocabulary."""
    print("Starting vocabulary translation...")
    print(f"Database: {DB_PATH}")

    # Connect to database
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Get all entries that need translation
    cursor.execute("""
        SELECT id, italian, word_type, level
        FROM vocabulary
        WHERE english = 'Translation needed'
        ORDER BY level, italian
    """)

    entries = cursor.fetchall()
    total = len(entries)
    print(f"\nFound {total} entries needing translation")

    # Track translations
    translated = 0
    needs_manual = 0
    manual_list = []

    # Translate each entry
    for entry_id, italian, word_type, level in entries:
        translation = translate_word(italian, word_type)

        if translation.startswith("NEEDS_MANUAL"):
            needs_manual += 1
            manual_list.append((entry_id, italian, word_type, level))
        else:
            # Update database
            cursor.execute("""
                UPDATE vocabulary
                SET english = ?
                WHERE id = ?
            """, (translation, entry_id))
            translated += 1

            if translated % 100 == 0:
                print(f"Progress: {translated}/{total} ({translated*100//total}%)")

    # Commit changes
    conn.commit()

    # Print summary
    print(f"\n{'='*60}")
    print(f"TRANSLATION SUMMARY")
    print(f"{'='*60}")
    print(f"Total entries processed: {total}")
    print(f"Successfully translated: {translated}")
    print(f"Needs manual translation: {needs_manual}")
    print(f"Success rate: {translated*100//total}%")

    # Save list of words needing manual translation
    if manual_list:
        output_file = Path(__file__).parent.parent / 'data' / 'needs_manual_translation.json'
        manual_data = [
            {'id': e[0], 'italian': e[1], 'word_type': e[2], 'level': e[3]}
            for e in manual_list
        ]
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(manual_data, f, indent=2, ensure_ascii=False)
        print(f"\nList of words needing manual translation saved to:")
        print(f"{output_file}")

    conn.close()
    print("\nTranslation complete!")


if __name__ == '__main__':
    main()

# Additional translations - Batch 2 (expanded vocabulary)
ADDITIONAL_TRANSLATIONS = {
    # More nouns
    'tavolo': 'table',
    'olio': 'oil',
    'barca': 'boat',
    'armadio': 'wardrobe, closet',
    'posta': 'mail, post office',
    'parola': 'word',
    'credito': 'credit',
    'centimetro': 'centimeter',
    'squadra': 'team',
    'agosto': 'August',
    'pazienza': 'patience',
    'crema': 'cream',
    'torta': 'cake',
    'pagina': 'page',
    'droga': 'drug',
    'collana': 'necklace',
    'pesce': 'fish',
    'stomaco': 'stomach',
    'vantaggio': 'advantage',
    'televisione': 'television',
    'treno': 'train',
    'scontrino': 'receipt',
    'nazionalità': 'nationality',
    'senato': 'senate',
    'schifo': 'disgust',
    'responsabilità': 'responsibility',
    'passeggiata': 'walk, stroll',
    'postino': 'mailman, postman',
    'bottone': 'button',
    'orologio': 'watch, clock',
    'scarpa': 'shoe',
    'occhiali': 'glasses',
    'piatto': 'plate, dish',
    'cucchiaio': 'spoon',
    'forchetta': 'fork',
    'coltello': 'knife',
    'tazza': 'cup',
    'bicchiere': 'glass',
    'tovaglia': 'tablecloth',
    'tovagliolo': 'napkin',
    'pentola': 'pot',
    'padella': 'pan',
    'forno': 'oven',
    'frigorifero': 'refrigerator',
    'lavandino': 'sink',
    'rubinetto': 'faucet, tap',
    'ascensore': 'elevator',
    'scala': 'stairs, ladder',
    'porta': 'door',
    'finestra': 'window',
    'muro': 'wall',
    'soffitto': 'ceiling',
    'pavimento': 'floor',
    'tetto': 'roof',
    'giardino': 'garden',
    'balcone': 'balcony',
    'terrazza': 'terrace',
    'garage': 'garage',
    'cantina': 'cellar',
    'sofà': 'sofa',
    'divano': 'couch, sofa',
    'sedia': 'chair',
    'tavola': 'table',
    'letto': 'bed',
    'cuscino': 'pillow',
    'coperta': 'blanket',
    'lenzuolo': 'sheet',
    'materasso': 'mattress',
    'lampada': 'lamp',
    'specchio': 'mirror',
    'quadro': 'painting, picture',
    'tappeto': 'carpet, rug',
    'tenda': 'curtain',
    'scatola': 'box',
    'valigia': 'suitcase',
    'zaino': 'backpack',
    'borsa': 'bag, purse',
    'portafoglio': 'wallet',
    'chiave': 'key',
    'serratura': 'lock',
    'ombrello': 'umbrella',
    'occhiali da sole': 'sunglasses',
    'cappello': 'hat',
    'berretto': 'cap',
    'sciarpa': 'scarf',
    'guanto': 'glove',
    'calzino': 'sock',
    'scarpa': 'shoe',
    'stivale': 'boot',
    'sandalo': 'sandal',
    'vestito': 'dress',
    'gonna': 'skirt',
    'pantaloni': 'pants, trousers',
    'jeans': 'jeans',
    'camicia': 'shirt',
    'maglietta': 'T-shirt',
    'maglione': 'sweater',
    'felpa': 'sweatshirt',
    'giacca': 'jacket',
    'cappotto': 'coat',
    'impermeabile': 'raincoat',
    'cravatta': 'tie',
    'cintura': 'belt',
    'bottone': 'button',
    'tasca': 'pocket',
    'zip': 'zipper',
    'orecchino': 'earring',
    'anello': 'ring',
    'braccialetto': 'bracelet',
    'collana': 'necklace',
    'orologio': 'watch',
    
    # Body parts
    'corpo': 'body',
    'testa': 'head',
    'capelli': 'hair',
    'faccia': 'face',
    'fronte': 'forehead',
    'occhio': 'eye',
    'sopracciglio': 'eyebrow',
    'ciglio': 'eyelash',
    'naso': 'nose',
    'bocca': 'mouth',
    'labbro': 'lip',
    'dente': 'tooth',
    'lingua': 'tongue',
    'guancia': 'cheek',
    'mento': 'chin',
    'orecchio': 'ear',
    'collo': 'neck',
    'gola': 'throat',
    'spalla': 'shoulder',
    'braccio': 'arm',
    'gomito': 'elbow',
    'polso': 'wrist',
    'mano': 'hand',
    'dito': 'finger',
    'unghia': 'nail',
    'pollice': 'thumb',
    'petto': 'chest',
    'seno': 'breast',
    'pancia': 'belly',
    'stomaco': 'stomach',
    'schiena': 'back',
    'fianco': 'side, hip',
    'gamba': 'leg',
    'coscia': 'thigh',
    'ginocchio': 'knee',
    'caviglia': 'ankle',
    'piede': 'foot',
    'tallone': 'heel',
    'cuore': 'heart',
    'polmone': 'lung',
    'fegato': 'liver',
    'rene': 'kidney',
    'sangue': 'blood',
    'pelle': 'skin',
    'osso': 'bone',
    'muscolo': 'muscle',
    
    # More verbs
    'aiutare': 'to help',
    'sposare': 'to marry',
    'divorziare': 'to divorce',
    'perdonare': 'to forgive',
    'continuare': 'to continue',
    'sedersi': 'to sit down',
    'peggiorare': 'to worsen',
    'riassumere': 'to summarize',
    'andarsene': 'to go away, to leave',
    'accendere': 'to turn on, to light',
    'spegnere': 'to turn off',
    'appendere': 'to hang',
    'attaccare': 'to attach, to attack',
    'aumentare': 'to increase',
    'avvertire': 'to warn',
    'baciare': 'to kiss',
    'ballare': 'to dance',
    'bussare': 'to knock',
    'cancellare': 'to erase, to delete',
    'caricare': 'to load, to charge',
    'cedere': 'to give in, to yield',
    'colpire': 'to hit',
    'comunicare': 'to communicate',
    'condividere': 'to share',
    'confondere': 'to confuse',
    'consegnare': 'to deliver',
    'consigliare': 'to advise',
    'controllare': 'to check, to control',
    'coprire': 'to cover',
    'crescere': 'to grow',
    'danneggiare': 'to damage',
    'descrivere': 'to describe',
    'desiderare': 'to wish, to desire',
    'determinare': 'to determine',
    'diminuire': 'to decrease',
    'dipendere': 'to depend',
    'dipingere': 'to paint',
    'dirigere': 'to direct',
    'disegnare': 'to draw',
    'distruggere': 'to destroy',
    'disturbare': 'to disturb',
    'diventare': 'to become',
    'dividere': 'to divide',
    'durare': 'to last',
    'emergere': 'to emerge',
    'esprimere': 'to express',
    'evitare': 'to avoid',
    'fiorire': 'to bloom',
    'firmare': 'to sign',
    'fissare': 'to fix, to stare',
    'fumare': 'to smoke',
    'funzionare': 'to work, to function',
    'garantire': 'to guarantee',
    'girare': 'to turn',
    'godere': 'to enjoy',
    'governare': 'to govern',
    'gridare': 'to shout',
    'guarire': 'to heal',
    'immaginare': 'to imagine',
    'impedire': 'to prevent',
    'indicare': 'to indicate',
    'influenzare': 'to influence',
    'informare': 'to inform',
    'interessare': 'to interest',
    'invitare': 'to invite',
    'lavare': 'to wash',
    'legare': 'to tie',
    'litigare': 'to argue, to quarrel',
    'meritare': 'to deserve',
    'migliorare': 'to improve',
    'misurare': 'to measure',
    'notare': 'to notice',
    'nuotare': 'to swim',
    'obbligare': 'to oblige',
    'occupare': 'to occupy',
    'odiare': 'to hate',
    'ordinare': 'to order',
    'organizzare': 'to organize',
    'osservare': 'to observe',
    'ottenere': 'to obtain',
    'paragonare': 'to compare',
    'parcheggiare': 'to park',
    'pettinare': 'to comb',
    'piacere': 'to please, to like',
    'piegare': 'to fold',
    'possedere': 'to possess',
    'prenotare': 'to book, to reserve',
    'preoccupare': 'to worry',
    'preservare': 'to preserve',
    'promettere': 'to promise',
    'pronunciare': 'to pronounce',
    'proporre': 'to propose',
    'proteggere': 'to protect',
    'pubblicare': 'to publish',
    'raccontare': 'to tell, to narrate',
    'raccogliere': 'to collect, to gather',
    'rappresentare': 'to represent',
    'realizzare': 'to realize, to achieve',
    'recitare': 'to act, to recite',
    'regalare': 'to give as a gift',
    'registrare': 'to record',
    'respingere': 'to reject',
    'restituire': 'to return, to give back',
    'ricordare': 'to remember',
    'rifiutare': 'to refuse',
    'rilassare': 'to relax',
    'ringraziare': 'to thank',
    'riparare': 'to repair',
    'rischiare': 'to risk',
    'riservare': 'to reserve',
    'risolvere': 'to solve',
    'risparmiare': 'to save (money)',
    'riuscire': 'to succeed',
    'rompere': 'to break',
    'rubare': 'to steal',
    'salutare': 'to greet',
    'salvare': 'to save',
    'scegliere': 'to choose',
    'sciare': 'to ski',
    'scusare': 'to excuse',
    'sembrare': 'to seem',
    'sognare': 'to dream',
    'sopportare': 'to bear, to stand',
    'sorridere': 'to smile',
    'sperare': 'to hope',
    'spiegare': 'to explain',
    'spostare': 'to move',
    'stampare': 'to print',
    'stirare': 'to iron',
    'stringere': 'to squeeze, to tighten',
    'succedere': 'to happen',
    'suggerire': 'to suggest',
    'superare': 'to overcome',
    'sviluppare': 'to develop',
    'svolgere': 'to carry out',
    'tagliare': 'to cut',
    'temere': 'to fear',
    'toccare': 'to touch',
    'tradurre': 'to translate',
    'trasferire': 'to transfer',
    'trasformare': 'to transform',
    'trattare': 'to treat',
    'uccidere': 'to kill',
    'unire': 'to unite',
    'urlare': 'to scream',
    'utilizzare': 'to use',
    'valere': 'to be worth',
    'verificare': 'to verify',
    'versare': 'to pour',
    'vietare': 'to forbid',
    'volare': 'to fly',
    'votare': 'to vote',
    
    # More adjectives
    'distinto': 'distinct, distinguished',
    'arancione': 'orange',
    'liquido': 'liquid',
    'avaro': 'greedy, stingy',
    'affettuoso': 'affectionate',
    'festivo': 'festive, holiday',
    'stesso': 'same',
    'mio': 'my',
    'tuo': 'your',
    'suo': 'his, her, its',
    'nostro': 'our',
    'vostro': 'your (plural)',
    'loro': 'their',
    'abbondante': 'abundant',
    'acceso': 'lit, on',
    'acuto': 'acute, sharp',
    'adatto': 'suitable',
    'affamato': 'hungry',
    'aggressivo': 'aggressive',
    'allegro': 'cheerful',
    'amaro': 'bitter',
    'amichevole': 'friendly',
    'ammalato': 'sick',
    'annoiato': 'bored',
    'ansioso': 'anxious',
    'arrabbiato': 'angry',
    'asciutto': 'dry',
    'assente': 'absent',
    'assoluto': 'absolute',
    'attento': 'attentive, careful',
    'attivo': 'active',
    'attuale': 'current',
    'audace': 'bold',
    'automat': 'automatic',
    'avanti': 'forward',
    'bagnato': 'wet',
    'bello': 'beautiful',
    'benedetto': 'blessed',
    'biondo': 'blond',
    'brillante': 'brilliant',
    'bruno': 'brown, dark-haired',
    'brutto': 'ugly',
    'buio': 'dark',
    'calmo': 'calm',
    'caro': 'dear, expensive',
    'casuale': 'casual, random',
    'cattivo': 'bad',
    'celebre': 'famous',
    'certo': 'certain',
    'chiarissimo': 'very clear',
    'cieco': 'blind',
    'classico': 'classic',
    'colpevole': 'guilty',
    'comodo': 'comfortable',
    'complesso': 'complex',
    'comune': 'common',
    'concreto': 'concrete',
    'confuso': 'confused',
    'conosciuto': 'known',
    'consapevole': 'aware',
    'conservatore': 'conservative',
    'considerevole': 'considerable',
    'continuo': 'continuous',
    'contrario': 'opposite',
    'convinto': 'convinced',
    'coraggioso': 'brave',
    'cordiale': 'cordial',
    'corretto': 'correct',
    'cortese': 'polite',
    'costante': 'constant',
    'costoso': 'expensive',
    'critico': 'critical',
    'crudele': 'cruel',
    'curioso': 'curious',
    'deciso': 'determined',
    'delicato': 'delicate',
    'delizioso': 'delicious',
    'democratico': 'democratic',
    'denso': 'dense',
    'deserto': 'deserted',
    'determinato': 'determined',
    'diligente': 'diligent',
    'dinamico': 'dynamic',
    'diretto': 'direct',
    'discreto': 'discreet',
    'disponibile': 'available',
    'distante': 'distant',
    'distratto': 'distracted',
    'divertente': 'fun, amusing',
    'divorziato': 'divorced',
    'dolce': 'sweet',
    'doloroso': 'painful',
    'domestico': 'domestic',
    'doppio': 'double',
    'drammatico': 'dramatic',
    'dritto': 'straight',
    'dubbioso': 'doubtful',
    'duro': 'hard',
    'eccellente': 'excellent',
    'eccessivo': 'excessive',
    'eccezionale': 'exceptional',
    'economico': 'economic, cheap',
    'educato': 'polite, educated',
    'efficace': 'effective',
    'efficiente': 'efficient',
    'egoista': 'selfish',
    'elegante': 'elegant',
    'elementare': 'elementary',
    'elevato': 'high, elevated',
    'emozione': 'emotion',
    'enorme': 'enormous',
    'entusiasta': 'enthusiastic',
    'esatto': 'exact',
    'esclusivo': 'exclusive',
    'esigente': 'demanding',
    'esile': 'slender',
    'esperto': 'expert',
    'essenziale': 'essential',
    'esterno': 'external',
    'estremo': 'extreme',
    'eterno': 'eternal',
    'evidente': 'evident',
    'familiare': 'familiar',
    'fantastico': 'fantastic',
    'faticoso': 'tiring',
    'favorevole': 'favorable',
    'favorito': 'favorite',
    'fedele': 'faithful',
    'feroce': 'fierce',
    'fertile': 'fertile',
    'festoso': 'festive',
    'fiero': 'proud',
    'finale': 'final',
    'fine': 'fine, thin',
    'fisico': 'physical',
    'fisso': 'fixed',
    'flessibile': 'flexible',
    'fluido': 'fluid',
    'formale': 'formal',
    'fortunato': 'lucky',
    'fragile': 'fragile',
    'franco': 'frank',
    'freddo': 'cold',
    'frequente': 'frequent',
    'fresco': 'fresh',
    'frettoloso': 'hasty',
    'frivolo': 'frivolous',
    'fu': 'was',
    'furioso': 'furious',
    'futuro': 'future',
    
    # Pronouns and articles
    'chiunque': 'anyone, whoever',
    'le': 'the (fem. pl.), her, them',
    
    # Common words
    'sconto': 'discount',
    'piano': 'slowly, gently',
    'alimentari': 'groceries, food items',
    
    # Months
    'gennaio': 'January',
    'febbraio': 'February',
    'marzo': 'March',
    'aprile': 'April',
    'maggio': 'May',
    'giugno': 'June',
    'luglio': 'July',
    'agosto': 'August',
    'settembre': 'September',
    'ottobre': 'October',
    'novembre': 'November',
    'dicembre': 'December',
    
    # Days
    'lunedì': 'Monday',
    'martedì': 'Tuesday',
    'mercoledì': 'Wednesday',
    'giovedì': 'Thursday',
    'venerdì': 'Friday',
    'sabato': 'Saturday',
    'domenica': 'Sunday',
    
    # Numbers
    'primo': 'first',
    'secondo': 'second',
    'terzo': 'third',
    'quarto': 'fourth',
    'quinto': 'fifth',
    'sesto': 'sixth',
    'settimo': 'seventh',
    'ottavo': 'eighth',
    'nono': 'ninth',
    'decimo': 'tenth',
    'undicesimo': 'eleventh',
    'dodicesimo': 'twelfth',
    'ventesimo': 'twentieth',
    'trentesimo': 'thirtieth',
    'centesimo': 'hundredth',
    'millesimo': 'thousandth',
    
    # Colors
    'rosso': 'red',
    'blu': 'blue',
    'giallo': 'yellow',
    'verde': 'green',
    'arancione': 'orange',
    'viola': 'purple',
    'rosa': 'pink',
    'marrone': 'brown',
    'grigio': 'grey',
    'nero': 'black',
    'bianco': 'white',
    'azzurro': 'light blue',
    
    # Time expressions
    'ieri': 'yesterday',
    'oggi': 'today',
    'domani': 'tomorrow',
    'dopodomani': 'day after tomorrow',
    'settimana': 'week',
    'mese': 'month',
    'anno': 'year',
    'secolo': 'century',
    'mattino': 'morning',
    'pomeriggio': 'afternoon',
    'sera': 'evening',
    'notte': 'night',
    'giorno': 'day',
    'ora': 'hour',
    'minuto': 'minute',
    'secondo': 'second',
    'momento': 'moment',
    'adesso': 'now',
    'presto': 'soon, early',
    'tardi': 'late',
    'sempre': 'always',
    'mai': 'never',
    'spesso': 'often',
    'raramente': 'rarely',
    'talvolta': 'sometimes',
    'ancora': 'still, yet, again',
    'già': 'already',
}

# Merge additional translations into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS)

# Additional translations - Batch 3
ADDITIONAL_TRANSLATIONS_3 = {
    # Common nouns - household
    'albergo': 'hotel',
    'alloggio': 'accommodation',
    'ascensore': 'elevator, lift',
    'baffo': 'mustache',
    'cantina': 'cellar, wine cellar',
    'lavastoviglie': 'dishwasher',
    'monolocale': 'studio apartment',
    'ombrello': 'umbrella',
    'passeggiata': 'walk, stroll',
    'prato': 'lawn, meadow',
    'tovagliolo': 'napkin',
    'vaglia': 'money order',
    
    # Body parts
    'piede': 'foot',
    'stomaco': 'stomach',
    
    # Food
    'pollo': 'chicken',
    'prosciutto': 'ham',
    'maiale': 'pork, pig',
    'ricetta': 'recipe, prescription',
    
    # Places & geography
    'agriturismo': 'farm stay',
    'dogana': 'customs',
    'est': 'east',
    'geografia': 'geography',
    'periferia': 'periphery, suburbs',
    'ufficio': 'office',
    
    # People & relationships
    'abitante': 'inhabitant, resident',
    'cognato': 'brother-in-law',
    'convivente': 'partner, cohabitant',
    'fidanzato': 'fiancé, boyfriend/girlfriend',
    'sindaco': 'mayor',
    'suocero': 'father-in-law',
    
    # Abstract nouns
    'artigianato': 'craftsmanship, handicraft',
    'articolo': 'article',
    'atteggiamento': 'attitude',
    'carriera': 'career',
    'diario': 'diary',
    'linea': 'line',
    'metallo': 'metal',
    'moneta': 'coin',
    'mutuo': 'mortgage',
    'nostalgia': 'nostalgia, homesickness',
    'odio': 'hatred',
    'partita': 'match, game',
    'polizia': 'police',
    'preposizione': 'preposition',
    'puzza': 'stench, bad smell',
    'risposta': 'answer, reply',
    'singolare': 'singular',
    'soldo': 'money, cent',
    'vacanza': 'vacation, holiday',
    'viaggio': 'trip, journey',
    'violenza': 'violence',
    'vino': 'wine',
    
    # Adjectives
    'affettuoso': 'affectionate',
    'antipatico': 'unpleasant, unlikeable',
    'buio': 'dark',
    'differente': 'different',
    'divertente': 'fun, amusing',
    'esterno': 'external, outside',
    'introverso': 'introverted',
    'marrone': 'brown',
    'minimo': 'minimum',
    'ovale': 'oval',
    'stesso': 'same',
    'ubriaco': 'drunk',
    
    # Verbs
    'accendere': 'to light, to turn on',
    'assumere': 'to hire, to assume',
    'comunicare': 'to communicate',
    'consegnare': 'to deliver, to hand over',
    'esprimere': 'to express',
    'fumare': 'to smoke',
    'girare': 'to turn, to spin',
    'iscriversi': 'to register, to enroll',
    'nascondere': 'to hide',
    'nevicare': 'to snow',
    'occupare': 'to occupy',
    'rubare': 'to steal',
    
    # Pronouns & particles
    'gli': 'to him, the (masc. pl.)',
    'i': 'the (masc. pl.)',
    'il': 'the (masc. sing.)',
    'li': 'them (masc.)',
    'lo': 'the (masc. sing.), him, it',
    'ne': 'of it, of them, some',
    'non': 'not',
    
    # Adverbs & expressions
    'almeno': 'at least',
    'cin-cin': 'cheers',
    'intanto': 'meanwhile, in the meantime',
    
    # Proper nouns & celebrations
    'Pasqua': 'Easter',
    
    # Technology
    'hobby': 'hobby',
    'hotel': 'hotel',
    'internet': 'internet',
    'televisione': 'television',
    
    # Nature
    'erba': 'grass, herb',
    'sole': 'sun',
    'stella': 'star',
    'stivale': 'boot',
    
    # Measurements
    'centimetro': 'centimeter',
    'millimetro': 'millimeter',
    
    # More common words from database
    'augurio': 'wish, greeting',
    'bacio': 'kiss',
    'femmina': 'female',
    'francobollo': 'stamp',
    'passaporto': 'passport',
    'penna': 'pen',
    'pepe': 'pepper',
    'pianta': 'plant',
}

# Merge batch 3 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_3)

# Additional translations - Batch 4
ADDITIONAL_TRANSLATIONS_4 = {
    # Common nouns - places & buildings
    'aeroporto': 'airport',
    'ambulatorio': 'clinic, outpatient facility',
    'bosco': 'wood, forest',
    'campeggio': 'camping, campsite',
    'clinica': 'clinic',
    'collegio': 'boarding school, college',
    'collina': 'hill',
    'confine': 'border, boundary',
    'fattoria': 'farm',
    'industria': 'industry',
    'istituto': 'institute',
    'lavanderia': 'laundry',
    'marciapiede': 'sidewalk',
    'ospedale': 'hospital',
    'parete': 'wall (interior)',
    'questura': 'police headquarters',
    'reparto': 'department, ward',
    'sala': 'room, hall',
    'soggiorno': 'living room, stay',
    'uscita': 'exit',
    'università': 'university',
    'villaggio': 'village',
    
    # Common nouns - objects
    'allarme': 'alarm',
    'arma': 'weapon',
    'binario': 'platform, track',
    'burro': 'butter',
    'busta': 'envelope',
    'cartolina': 'postcard',
    'cd': 'CD',
    'cibo': 'food',
    'e-mail': 'email',
    'esercizio': 'exercise',
    'giocattolo': 'toy',
    'manica': 'sleeve',
    'motorino': 'moped, scooter',
    'paio': 'pair',
    'pasta': 'pasta',
    'pettine': 'comb',
    'poltrona': 'armchair',
    'posto': 'place, seat',
    'punto': 'point',
    'racchetta': 'racket',
    'romanzo': 'novel',
    'sigaro': 'cigar',
    'spaghetto': 'spaghetti',
    'spuntino': 'snack',
    'taxi': 'taxi',
    'termometro': 'thermometer',
    'verbo': 'verb',
    
    # Common nouns - abstract
    'affitto': 'rent',
    'assicurazione': 'insurance',
    'attentato': 'attack, bombing',
    'attesa': 'wait, waiting',
    'carnevale': 'carnival',
    'condoglianza': 'condolence',
    'divertimento': 'fun, entertainment',
    'documentario': 'documentary',
    'elezione': 'election',
    'facoltà': 'faculty, ability',
    'giro': 'tour, round',
    'lotto': 'lottery',
    'medicina': 'medicine',
    'mittente': 'sender',
    'musicale': 'musical',
    'pena': 'penalty, punishment',
    'previsione': 'forecast, prediction',
    'prezzo': 'price',
    'processo': 'process, trial',
    'pronome': 'pronoun',
    'raffreddore': 'cold (illness)',
    'ricordo': 'memory, souvenir',
    'riscaldamento': 'heating',
    'sapore': 'flavor, taste',
    'senso': 'sense, meaning',
    'settimanale': 'weekly',
    'sinistra': 'left',
    'situazione': 'situation',
    'sport': 'sport',
    'talk-show': 'talk show',
    'temporale': 'storm',
    'tennis': 'tennis',
    'terrorismo': 'terrorism',
    'tragedia': 'tragedy',
    'umore': 'mood, humor',
    'velocità': 'speed',
    
    # People
    'canguro': 'kangaroo, babysitter',
    'compagno': 'companion, partner',
    'dipendente': 'employee',
    'maschio': 'male',
    'parente': 'relative',
    'presidente': 'president',
    'ragazzo': 'boy, boyfriend',
    'turista': 'tourist',
    'vigile': 'traffic officer, police officer',
    
    # Adjectives
    'accanto': 'next to, beside',
    'alcuno': 'some, any',
    'appassionato': 'passionate',
    'aspro': 'sour, harsh',
    'benvenuto': 'welcome',
    'casalingo': 'homemade, domestic',
    'contante': 'cash',
    'finto': 'fake, false',
    'impaziente': 'impatient',
    'indietro': 'back, behind',
    'intelligente': 'intelligent',
    'meraviglioso': 'wonderful, marvelous',
    'noioso': 'boring',
    'nessuno': 'no one, none',
    'pallacanestro': 'basketball',
    'quotidiano': 'daily',
    'rettangolare': 'rectangular',
    'riccio': 'curly',
    'seguente': 'following, next',
    'socievole': 'sociable',
    'solido': 'solid',
    'soltanto': 'only',
    
    # Verbs
    'accettare': 'to accept',
    'addormentarsi': 'to fall asleep',
    'altrimenti': 'otherwise',
    'annoiarsi': 'to get bored',
    'calmarsi': 'to calm down',
    'correggere': 'to correct',
    'criticare': 'to criticize',
    'cuocere': 'to cook',
    'dimostrare': 'to demonstrate, to show',
    'diplomarsi': 'to graduate',
    'disperare': 'to despair',
    'farcela': 'to make it, to manage',
    'fidarsi': 'to trust',
    'inventare': 'to invent',
    'mancare': 'to miss, to lack',
    'pranzare': 'to have lunch',
    'riposare': 'to rest',
    'spaventare': 'to scare, to frighten',
    'spingere': 'to push',
    'sopravvivere': 'to survive',
    'sottolineare': 'to underline, to emphasize',
    'ubriacarsi': 'to get drunk',
    
    # Conjunctions & particles
    'pure': 'also, too',
    'purché': 'provided that, as long as',
    
    # Exclamations
    'accidenti': 'darn, damn',
}

# Merge batch 4 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_4)

# Additional translations - Batch 5
ADDITIONAL_TRANSLATIONS_5 = {
    # Common nouns - places
    'aula': 'classroom',
    'autostrada': 'highway, motorway',
    'capitale': 'capital',
    'consolato': 'consulate',
    'ditta': 'company, firm',
    'metropoli': 'metropolis',
    'municipio': 'town hall, city hall',
    'palazzo': 'palace, building',
    'parco': 'park',
    'pizzeria': 'pizzeria',
    'ponte': 'bridge',
    'prigione': 'prison',
    'scuola': 'school',
    'studio': 'study, office',
    'supermercato': 'supermarket',
    'teatro': 'theater',
    
    # Common nouns - objects
    'accendino': 'lighter',
    'barba': 'beard',
    'benzina': 'gasoline',
    'cadavere': 'corpse',
    'camion': 'truck',
    'camper': 'camper, RV',
    'cappuccino': 'cappuccino',
    'cassa': 'cash register, box',
    'cioccolato': 'chocolate',
    'copia': 'copy',
    'data': 'date',
    'dentifricio': 'toothpaste',
    'dettato': 'dictation',
    'dizionario': 'dictionary',
    'doccia': 'shower',
    'fiammifero': 'match',
    'frase': 'sentence, phrase',
    'lavagna': 'blackboard, whiteboard',
    'messaggio': 'message',
    'opera': 'opera, work',
    'palla': 'ball',
    'pistola': 'pistol, gun',
    'profumo': 'perfume',
    'pubblicità': 'advertising',
    'quaderno': 'notebook',
    'radio': 'radio',
    'regalo': 'gift, present',
    'rivista': 'magazine',
    'salsa': 'sauce',
    'sms': 'text message, SMS',
    'spazzolino': 'toothbrush',
    'tè': 'tea',
    'vaso': 'vase, pot',
    'vetro': 'glass',
    'visto': 'visa',
    
    # Food & cooking
    'aglio': 'garlic',
    'antipasto': 'appetizer',
    'calcio': 'soccer, calcium',
    'carota': 'carrot',
    'commedia': 'comedy',
    'dispensa': 'pantry',
    'merenda': 'snack',
    'prezzemolo': 'parsley',
    'spicchio': 'clove, segment',
    
    # People & professions
    'anziano': 'elderly, senior',
    'attore': 'actor',
    'cantante': 'singer',
    'capo': 'boss, head',
    'collaboratore': 'collaborator',
    'coniuge': 'spouse',
    'padrone': 'owner, master',
    'papà': 'dad',
    'pittore': 'painter',
    'poeta': 'poet',
    'scrittore': 'writer',
    'scultore': 'sculptor',
    'signore': 'sir, mister, gentleman',
    'straniero': 'foreigner',
    'tecnico': 'technician',
    'uccello': 'bird',
    'vigile': 'traffic officer',
    'zio': 'uncle',
    
    # Abstract nouns
    'accordo': 'agreement',
    'amicizia': 'friendship',
    'aria': 'air',
    'avverbio': 'adverb',
    'capodanno': 'New Year',
    'causa': 'cause',
    'check-in': 'check-in',
    'cognome': 'surname, last name',
    'concerto': 'concert',
    'coraggio': 'courage',
    'debito': 'debt',
    'dieta': 'diet',
    'dipinto': 'painting',
    'direzione': 'direction',
    'divieto': 'prohibition, ban',
    'dolore': 'pain',
    'dottorato': 'doctorate, PhD',
    'fatica': 'fatigue, effort',
    'gara': 'race, competition',
    'identità': 'identity',
    'immobile': 'real estate, property',
    'impegno': 'commitment, engagement',
    'importanza': 'importance',
    'impressione': 'impression',
    'incendio': 'fire',
    'la': 'the (fem. sing.), her, it',
    'lordo': 'gross',
    'malattia': 'illness, disease',
    'marca': 'brand',
    'master': 'master\'s degree',
    'maternità': 'maternity',
    'maturità': 'maturity, high school diploma',
    'odore': 'smell, odor',
    'ovest': 'west',
    'paga': 'pay, wage',
    'partenza': 'departure',
    'pensione': 'pension, retirement',
    'possibilità': 'possibility',
    'prefisso': 'prefix, area code',
    'presenza': 'presence',
    'probabilità': 'probability',
    'ragione': 'reason',
    'relazione': 'relationship, report',
    'saggio': 'essay, wise',
    'sciopero': 'strike',
    'sete': 'thirst',
    'sfortuna': 'bad luck',
    'soluzione': 'solution',
    'tosse': 'cough',
    'un': 'a, an (masc.)',
    'vento': 'wind',
    
    # Adjectives
    'capace': 'capable',
    'corrente': 'current',
    'crudo': 'raw',
    'gratis': 'free',
    'inutile': 'useless',
    'lavorativo': 'work-related',
    'liscio': 'smooth',
    'magnifico': 'magnificent',
    'mite': 'mild',
    'nuvoloso': 'cloudy',
    'obbligatorio': 'mandatory, compulsory',
    'ottimista': 'optimistic',
    'ruvido': 'rough',
    'tiepido': 'lukewarm, tepid',
    'timido': 'shy',
    
    # Verbs
    'affittare': 'to rent',
    'ammettere': 'to admit',
    'bocciare': 'to fail (an exam), to reject',
    'bruciarsi': 'to burn oneself',
    'calcolare': 'to calculate',
    'cenare': 'to have dinner',
    'chiacchierare': 'to chat',
    'chiedere': 'to ask',
    'chiamare': 'to call',
    'collezionare': 'to collect',
    'combattere': 'to fight',
    'comprendere': 'to understand, to include',
    'condannare': 'to condemn',
    'condizionare': 'to condition',
    'crepare': 'to die, to burst',
    'curarsi': 'to take care of oneself',
    'frequentare': 'to attend, to frequent',
    'includere': 'to include',
    'indossare': 'to wear',
    'lavare': 'to wash',
    'mettere': 'to put',
    'moltiplicare': 'to multiply',
    'muovere': 'to move',
    'partecipare': 'to participate',
    'passeggiare': 'to walk, to stroll',
    'pescare': 'to fish',
    'piovere': 'to rain',
    'reagire': 'to react',
    'rilassarsi': 'to relax',
    'spogliarsi': 'to undress',
    'sporcare': 'to dirty, to soil',
    'sposare': 'to marry',
    'terrorizzare': 'to terrorize',
    'usare': 'to use',
    'vestirsi': 'to get dressed',
    
    # Adverbs & expressions
    'cioè': 'that is, namely',
    'eccetto': 'except',
    'infine': 'finally',
    'insomma': 'in short, well',
    'particolarmente': 'particularly',
    'presso': 'at, near',
    'qui': 'here',
    'sollecito': 'prompt',
    
    # Measurements
    'chilometro': 'kilometer',
}

# Merge batch 5 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_5)

# Additional translations - Batch 6
ADDITIONAL_TRANSLATIONS_6 = {
    # Common nouns - places & things
    'ambulanza': 'ambulance',
    'angolo': 'corner, angle',
    'bagaglio': 'luggage',
    'banana': 'banana',
    'bancomat': 'ATM',
    'biglietteria': 'ticket office',
    'birra': 'beer',
    'calza': 'sock, stocking',
    'cassettiera': 'dresser, chest of drawers',
    'cellulare': 'cell phone',
    'cena': 'dinner',
    'cimitero': 'cemetery',
    'comodino': 'nightstand',
    'cura': 'care, treatment',
    'distanza': 'distance',
    'duomo': 'cathedral',
    'economia': 'economy',
    'ferita': 'wound, injury',
    'ferro': 'iron',
    'fumetto': 'comic book',
    'gas': 'gas',
    'guida': 'guide',
    'incubo': 'nightmare',
    'intervista': 'interview',
    'leone': 'lion',
    'lirica': 'opera, lyric poetry',
    'lupo': 'wolf',
    'matematica': 'mathematics',
    'multa': 'fine, ticket',
    'occhiale': 'eyeglasses',
    'oggetto': 'object',
    'ordine': 'order',
    'pacco': 'package, parcel',
    'panino': 'sandwich',
    'parcheggio': 'parking',
    'parte': 'part',
    'passaggio': 'passage, ride',
    'patata': 'potato',
    'patente': 'driver\'s license',
    'peccato': 'sin, pity',
    'personaggio': 'character, personality',
    'pezzo': 'piece',
    'phon': 'hair dryer',
    'pipa': 'pipe',
    'piscina': 'swimming pool',
    'pizzico': 'pinch',
    'posata': 'cutlery',
    'presentazione': 'presentation',
    'prodotto': 'product',
    'raccomandata': 'registered mail',
    'reclamo': 'complaint',
    'resto': 'rest, change (money)',
    'riscontro': 'feedback, response',
    'roba': 'stuff, things',
    'salame': 'salami',
    'salita': 'climb, ascent',
    'salotto': 'living room',
    'sapone': 'soap',
    'scaffale': 'shelf',
    'sci': 'ski',
    'scienza': 'science',
    'sciroppo': 'syrup',
    'seguito': 'continuation, following',
    'serata': 'evening',
    'sonno': 'sleep',
    'stanza': 'room',
    'sud': 'south',
    'telegramma': 'telegram',
    'telefonata': 'phone call',
    'terapia': 'therapy',
    'traffico': 'traffic',
    'tramonto': 'sunset',
    'tuono': 'thunder',
    'tv': 'TV',
    'uomo': 'man',
    'vagone': 'wagon, train car',
    'viso': 'face',
    'vita': 'life',
    
    # Abstract nouns
    'abbonamento': 'subscription',
    'accento': 'accent',
    'agio': 'comfort, ease',
    'analisi': 'analysis',
    'appetito': 'appetite',
    'capacità': 'capacity, ability',
    'collezione': 'collection',
    'compito': 'task, homework',
    'concorso': 'competition, contest',
    'congratulazione': 'congratulations',
    'cortesia': 'courtesy',
    'esame': 'exam',
    'favola': 'fairy tale',
    'febbre': 'fever',
    'fortuna': 'luck, fortune',
    'genere': 'gender, kind',
    'inizio': 'beginning',
    'inquilino': 'tenant',
    'livello': 'level',
    'militare': 'military',
    'opinione': 'opinion',
    'proposito': 'purpose, intention',
    'questione': 'question, issue',
    'saldo': 'sale, balance',
    'scopo': 'purpose, goal',
    'soldato': 'soldier',
    'valore': 'value',
    
    # People
    'autore': 'author',
    'capello': 'hair',
    'celibe': 'bachelor, single',
    'genero': 'son-in-law',
    'giocatore': 'player',
    'giornalista': 'journalist',
    'idraulico': 'plumber',
    'maestro': 'teacher, master',
    'meccanico': 'mechanic',
    'ministro': 'minister',
    'segretario': 'secretary',
    
    # Adjectives
    'acido': 'acid, sour',
    'allergico': 'allergic',
    'assolutamente': 'absolutely',
    'castano': 'brown (hair)',
    'contemporaneo': 'contemporary',
    'disabile': 'disabled',
    'generoso': 'generous',
    'improvviso': 'sudden',
    'invisibile': 'invisible',
    'minuscolo': 'tiny, lowercase',
    'nervoso': 'nervous',
    'orribile': 'horrible',
    'pessimo': 'very bad, worst',
    'piacevole': 'pleasant',
    'scorretto': 'incorrect, improper',
    
    # Verbs
    'acqua': 'water',
    'acquistare': 'to purchase',
    'aggiungere': 'to add',
    'andare': 'to go',
    'apprezzare': 'to appreciate',
    'arrabbiarsi': 'to get angry',
    'bagnare': 'to wet',
    'bisognare': 'to be necessary',
    'bollire': 'to boil',
    'chiamare': 'to call',
    'catturare': 'to capture',
    'confermare': 'to confirm',
    'connettersi': 'to connect',
    'costruire': 'to build',
    'detestare': 'to detest, to hate',
    'dubitare': 'to doubt',
    'esistere': 'to exist',
    'ferire': 'to injure, to wound',
    'incominciare': 'to begin',
    'incontrare': 'to meet',
    'innamorarsi': 'to fall in love',
    'laurearsi': 'to graduate (university)',
    'navigare': 'to navigate, to surf',
    'noleggiare': 'to rent',
    'occupare': 'to occupy',
    'prendersela': 'to take it badly, to get upset',
    'proibire': 'to prohibit',
    'rendere': 'to render, to make',
    'riguardare': 'to concern, to regard',
    'rompere': 'to break',
    'scherzare': 'to joke',
    'separare': 'to separate',
    'significare': 'to mean',
    'stendere': 'to spread, to hang out',
    'stressare': 'to stress',
    'trasportare': 'to transport',
    
    # Adverbs & conjunctions
    'affinché': 'so that, in order that',
    'beh': 'well',
    'entro': 'within, by',
    'finché': 'until, as long as',
    'finora': 'until now, so far',
    'inoltre': 'moreover, furthermore',
    'improvvisamente': 'suddenly',
    'infatti': 'in fact, indeed',
    'lentamente': 'slowly',
    'oggigiorno': 'nowadays',
    'parere': 'to seem, opinion',
    'sennò': 'otherwise',
    
    # Measurements
    'litro': 'liter',
    'quintale': 'quintal (100 kg)',
    
    # Common phrases
    'bibita': 'drink, beverage',
}

# Merge batch 6 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_6)

# Additional translations - Batch 7
ADDITIONAL_TRANSLATIONS_7 = {
    # Common nouns - places & institutions
    'alba': 'dawn',
    'biblioteca': 'library',
    'clima': 'climate',
    'condominio': 'condominium',
    'discoteca': 'disco, nightclub',
    'incrocio': 'intersection, crossing',
    'mensola': 'shelf',
    'piazza': 'square, plaza',
    'provincia': 'province',
    'rotatoria': 'roundabout',
    'torre': 'tower',
    'vetrina': 'shop window, display',
    
    # Common nouns - objects
    'aperitivo': 'aperitif',
    'arancia': 'orange',
    'asciugamano': 'towel',
    'bambola': 'doll',
    'cervello': 'brain',
    'coda': 'tail, queue',
    'fax': 'fax',
    'fornello': 'stove, burner',
    'fulmine': 'lightning',
    'impianto': 'plant, system',
    'lavatrice': 'washing machine',
    'mensile': 'monthly',
    'oro': 'gold',
    'pantalone': 'pants, trousers',
    'posacenere': 'ashtray',
    'riso': 'rice, laughter',
    'roulotte': 'trailer, caravan',
    'ruota': 'wheel',
    'sale': 'salt',
    'scultura': 'sculpture',
    'sigaretta': 'cigarette',
    'tariffa': 'rate, fare',
    'telefono': 'telephone',
    'telefilm': 'TV series',
    'tombola': 'bingo',
    'tonnellata': 'ton',
    'virgola': 'comma',
    'voce': 'voice',
    'zucchero': 'sugar',
    
    # Abstract nouns
    'affare': 'business, deal',
    'ansia': 'anxiety',
    'anticipo': 'advance',
    'arrivo': 'arrival',
    'associazione': 'association',
    'aumento': 'increase',
    'bugia': 'lie',
    'calma': 'calm',
    'coincidenza': 'coincidence',
    'colpa': 'fault, guilt',
    'compagnia': 'company',
    'complimento': 'compliment',
    'condizione': 'condition',
    'conferenza': 'conference',
    'costruzione': 'construction',
    'cui': 'which, whom',
    'delusione': 'disappointment',
    'denuncia': 'report, complaint',
    'dialogo': 'dialogue',
    'difficoltà': 'difficulty',
    'fastidio': 'annoyance',
    'fondo': 'bottom, fund',
    'forza': 'strength, force',
    'ginnastica': 'gymnastics',
    'immagine': 'image',
    'laurea': 'degree',
    'ok': 'OK',
    'ospitalità': 'hospitality',
    'partito': 'party (political)',
    'passione': 'passion',
    'pasto': 'meal',
    'paura': 'fear',
    'pausa': 'pause, break',
    'periodo': 'period',
    'persona': 'person',
    'pietà': 'pity, mercy',
    'pittura': 'painting',
    'poesia': 'poetry',
    'primavera': 'spring',
    'problema': 'problem',
    'rispetto': 'respect',
    'ritardo': 'delay',
    'salute': 'health',
    'saluto': 'greeting',
    'schiera': 'row, rank',
    'segreteria': 'secretary\'s office, voicemail',
    'soccorso': 'help, aid',
    'sogno': 'dream',
    'spesa': 'expense, shopping',
    'spettacolo': 'show, spectacle',
    'stato': 'state',
    'stop': 'stop',
    'svantaggio': 'disadvantage',
    'tecnologia': 'technology',
    'tempo': 'time, weather',
    'torto': 'wrong',
    'tratto': 'trait, stretch',
    'tranquillità': 'tranquility',
    'trasmissione': 'transmission, broadcast',
    'vi': 'you (plural), there',
    'volontà': 'will, willingness',
    
    # People & professions
    'azienda': 'company',
    'commesso': 'sales clerk',
    'Papa': 'Pope',
    'pediatra': 'pediatrician',
    'prete': 'priest',
    'professore': 'professor, teacher',
    
    # Adjectives
    'egregio': 'dear, esteemed',
    'femminile': 'feminine',
    'impensabile': 'unthinkable',
    'improbabile': 'improbable',
    'indispensabile': 'indispensable',
    'maschile': 'masculine',
    'matto': 'crazy, mad',
    'Natale': 'Christmas',
    'positivo': 'positive',
    'porco': 'dirty, pig',
    'pronto': 'ready',
    'quadrato': 'square',
    'ridicolo': 'ridiculous',
    'rischioso': 'risky',
    'spettabile': 'esteemed (in letters)',
    'sportivo': 'sporty, athletic',
    'trasparente': 'transparent',
    'vedovo': 'widower, widowed',
    
    # Verbs
    'abbandonare': 'to abandon',
    'abbracciare': 'to hug, to embrace',
    'adoperare': 'to use',
    'affrontare': 'to face, to confront',
    'aggiustare': 'to fix, to repair',
    'alzarsi': 'to get up',
    'ammalarsi': 'to get sick',
    'ammirare': 'to admire',
    'attraversare': 'to cross',
    'capitare': 'to happen',
    'complicare': 'to complicate',
    'convincere': 'to convince',
    'divertirsi': 'to have fun',
    'escludere': 'to exclude',
    'fermare': 'to stop',
    'fregarsene': 'to not care, to not give a damn',
    'friggere': 'to fry',
    'guadagnare': 'to earn',
    'gustare': 'to taste, to enjoy',
    'iniziare': 'to begin',
    'intendere': 'to intend, to understand',
    'interessarsi': 'to be interested',
    'inviare': 'to send',
    'lamentarsi': 'to complain',
    'lavare': 'to wash',
    'preoccuparsi': 'to worry',
    'prestare': 'to lend',
    'raccomandarsi': 'to recommend oneself, to beg',
    'riflettere': 'to reflect',
    'rinunciare': 'to give up',
    'ritirare': 'to withdraw, to collect',
    'ritrovare': 'to find again',
    'scaricare': 'to unload, to download',
    'scoprire': 'to discover',
    'sentire': 'to hear, to feel',
    'sfruttare': 'to exploit',
    'soffrire': 'to suffer',
    'sospendere': 'to suspend',
    'sottrarre': 'to subtract',
    'togliere': 'to remove, to take off',
    'trascorrere': 'to spend (time)',
    'trasferirsi': 'to move, to transfer',
    'traslocare': 'to move (house)',
    'vergognarsi': 'to be ashamed',
    
    # Conjunctions & interjections
    'addio': 'goodbye, farewell',
    'cavallo': 'horse',
    'contorno': 'side dish, contour',
    'mah': 'well, I don\'t know',
    'praticamente': 'practically',
    'siccome': 'since, as',
}

# Merge batch 7 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_7)

# Additional translations - Batch 8 (Final major batch)
ADDITIONAL_TRANSLATIONS_8 = {
    # Common nouns - places
    'banco': 'desk, bench, bank counter',
    'cantiere': 'construction site',
    'carcere': 'prison',
    'chiesa': 'church',
    'cima': 'top, peak',
    'distributore': 'distributor, dispenser',
    'fiume': 'river',
    'galleria': 'gallery, tunnel',
    'paese': 'country, village',
    'porto': 'port, harbor',
    'quartiere': 'neighborhood, quarter',
    'repubblica': 'republic',
    'ristorante': 'restaurant',
    'scrivania': 'desk',
    'semaforo': 'traffic light',
    'spiaggia': 'beach',
    'stadio': 'stadium',
    'stazione': 'station',
    'strada': 'street, road',
    'vasca': 'tub, basin',
    'villa': 'villa',
    'water': 'toilet',
    
    # Common nouns - food
    'arrosto': 'roast',
    'bistecca': 'steak',
    'caffè': 'coffee',
    'fetta': 'slice',
    'pane': 'bread',
    'pera': 'pear',
    'pillola': 'pill',
    'pisello': 'pea',
    'pizza': 'pizza',
    'pomodoro': 'tomato',
    'pranzo': 'lunch',
    
    # Common nouns - objects
    'argento': 'silver',
    'assegno': 'check',
    'auto': 'car',
    'banconota': 'banknote',
    'bilancia': 'scale, balance',
    'bolletta': 'bill',
    'bollettino': 'bulletin',
    'cerotto': 'band-aid',
    'curriculum vitae': 'resume, CV',
    'diploma': 'diploma',
    'emergenza': 'emergency',
    'ghiaccio': 'ice',
    'mancia': 'tip',
    'plastica': 'plastic',
    'polizza': 'policy (insurance)',
    'rock': 'rock (music)',
    'sacco': 'sack, bag',
    'shampoo': 'shampoo',
    'sillaba': 'syllable',
    'stage': 'internship',
    'stress': 'stress',
    'tigre': 'tiger',
    'virgoletta': 'quotation mark',
    
    # Abstract nouns
    'abitudine': 'habit',
    'alimentazione': 'nutrition, diet',
    'armonia': 'harmony',
    'attimo': 'moment',
    'bisogno': 'need',
    'ciascuno': 'each one',
    'ciò': 'that, this',
    'colloquio': 'interview',
    'commento': 'comment',
    'comunicazione': 'communication',
    'coppia': 'couple',
    'costo': 'cost',
    'crociera': 'cruise',
    'cultura': 'culture',
    'danno': 'damage',
    'destinatario': 'recipient',
    'diavolo': 'devil',
    'differenza': 'difference',
    'difetto': 'defect, flaw',
    'discussione': 'discussion',
    'etto': 'hectogram (100g)',
    'feriale': 'weekday',
    'fiducia': 'trust',
    'folla': 'crowd',
    'forma': 'form, shape',
    'fornitore': 'supplier',
    'furto': 'theft',
    'gesto': 'gesture',
    'gioia': 'joy',
    'giustizia': 'justice',
    'intenzione': 'intention',
    'maiuscola': 'capital letter, uppercase',
    'maniera': 'manner, way',
    'messa': 'mass (religious)',
    'miseria': 'misery, poverty',
    'né': 'neither, nor',
    'offerta': 'offer',
    'opportunità': 'opportunity',
    'ospite': 'guest, host',
    'pace': 'peace',
    'plurale': 'plural',
    'precedenza': 'priority, precedence',
    'programma': 'program',
    'pronuncia': 'pronunciation',
    'protagonista': 'protagonist',
    'qualità': 'quality',
    'rapina': 'robbery',
    'rapporto': 'relationship, report',
    'regola': 'rule',
    'ricchezza': 'wealth',
    'risultato': 'result',
    'sbaglio': 'mistake',
    'sesso': 'sex, gender',
    'silenzio': 'silence',
    'storia': 'story, history',
    'stiro': 'ironing',
    'temperatura': 'temperature',
    'tensione': 'tension',
    'titolo': 'title',
    'verità': 'truth',
    
    # People & professions
    'addetto': 'employee, attendant',
    'amministratore': 'administrator',
    'criminale': 'criminal',
    'dentista': 'dentist',
    'dottore': 'doctor',
    'elettricista': 'electrician',
    'preside': 'principal, dean',
    'studente': 'student',
    'suora': 'nun',
    
    # Adjectives
    'abbastanza': 'enough',
    'adulto': 'adult',
    'attentamente': 'carefully',
    'autentico': 'authentic',
    'chilo': 'kilo',
    'continuamente': 'continuously',
    'dappertutto': 'everywhere',
    'estroverso': 'extroverted',
    'figo': 'cool',
    'guasto': 'broken, out of order',
    'ideale': 'ideal',
    'incredibile': 'incredible',
    'indifferente': 'indifferent',
    'indimenticabile': 'unforgettable',
    'innanzitutto': 'first of all',
    'insipido': 'tasteless',
    'massimo': 'maximum',
    'nonostante': 'despite, notwithstanding',
    'nubile': 'single, unmarried (woman)',
    'pazzesco': 'crazy, incredible',
    'piccante': 'spicy',
    'precedente': 'previous',
    'tradizionale': 'traditional',
    'ulteriore': 'further',
    'variabile': 'variable',
    'vegetariano': 'vegetarian',
    
    # Verbs
    'abituarsi': 'to get used to',
    'accarezzare': 'to caress, to pet',
    'accorgersi': 'to realize, to notice',
    'accompagnare': 'to accompany',
    'adottare': 'to adopt',
    'annullare': 'to cancel',
    'arrestare': 'to arrest',
    'attendere': 'to wait',
    'avvicinarsi': 'to approach',
    'bagnare': 'to wet',
    'boh': 'I don\'t know (interjection)',
    'buttare': 'to throw',
    'citare': 'to quote, to cite',
    'cliccare': 'to click',
    'colorare': 'to color',
    'commentare': 'to comment',
    'comportarsi': 'to behave',
    'contattare': 'to contact',
    'creare': 'to create',
    'dichiarare': 'to declare',
    'disoccupato': 'unemployed',
    'dispiacere': 'to be sorry, to displease',
    'fermarsi': 'to stop',
    'imitare': 'to imitate',
    'importare': 'to import, to matter',
    'incontrare': 'to meet',
    'intervenire': 'to intervene',
    'lasciare': 'to leave, to let',
    'muovere': 'to move',
    'pesare': 'to weigh',
    'piegare': 'to fold, to bend',
    'porgere': 'to hand, to offer',
    'pregare': 'to pray, to beg',
    'premere': 'to press',
    'promuovere': 'to promote',
    'puzzare': 'to stink',
    'raggiungere': 'to reach',
    'rallentare': 'to slow down',
    'ricordare': 'to remember',
    'rompere': 'to break',
    'saltare': 'to jump, to skip',
    'vedere': 'to see',
    'vedersi': 'to see each other, to meet',
    'sentire': 'to hear, to feel',
    'separare': 'to separate',
    'sparare': 'to shoot',
    'specializzarsi': 'to specialize',
    'sposare': 'to marry',
    'svegliare': 'to wake up',
    'terminare': 'to finish, to end',
}

# Merge batch 8 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_8)

# Additional translations - Batch 9
ADDITIONAL_TRANSLATIONS_9 = {
    # Common nouns - places & institutions
    'abitazione': 'dwelling, residence',
    'asilo': 'kindergarten, asylum',
    'base': 'base',
    'canale': 'channel',
    'cittadinanza': 'citizenship',
    'galera': 'prison, jail',
    'ghiacciaio': 'glacier',
    'liceo': 'high school',
    'mura': 'walls (city walls)',
    'palestra': 'gym',
    'sede': 'headquarters, seat',
    'sistema': 'system',
    'sito': 'site',
    'società': 'society, company',
    'terra': 'earth, ground',
    
    # Common nouns - objects
    'abbraccio': 'hug, embrace',
    'acconto': 'deposit, down payment',
    'bomba': 'bomb',
    'canale': 'channel',
    'carattere': 'character',
    'contratto': 'contract',
    'cronaca': 'news, chronicle',
    'dato': 'data, datum',
    'elicottero': 'helicopter',
    'farina': 'flour',
    'feria': 'holiday, day off',
    'fiction': 'fiction, TV drama',
    'freezer': 'freezer',
    'freno': 'brake',
    'merce': 'goods, merchandise',
    'modulo': 'form, module',
    'occasione': 'occasion, opportunity',
    'padre': 'father',
    'permesso': 'permission, permit',
    'pop': 'pop (music)',
    'pulizia': 'cleaning',
    'rata': 'installment',
    'sé': 'self',
    'seta': 'silk',
    'somma': 'sum',
    'stipendio': 'salary',
    'termosifone': 'radiator',
    'tipo': 'type, guy',
    'tortellino': 'tortellini',
    'tostapane': 'toaster',
    'trasloco': 'move, relocation',
    'uovo': 'egg',
    'volta': 'time, turn',
    
    # Abstract nouns
    'affermazione': 'statement, affirmation',
    'annuncio': 'announcement',
    'assenza': 'absence',
    'carattere': 'character',
    'commercio': 'commerce, trade',
    'conclusione': 'conclusion',
    'conseguenza': 'consequence',
    'contatto': 'contact',
    'desiderio': 'desire',
    'dipendenza': 'dependence',
    'discesa': 'descent',
    'espressione': 'expression',
    'formazione': 'training, formation',
    'gioco': 'game',
    'ideologia': 'ideology',
    'inquinamento': 'pollution',
    'minuscola': 'lowercase',
    'occasione': 'occasion',
    'orario': 'schedule, timetable',
    'organizzazione': 'organization',
    'paesaggio': 'landscape',
    'pagamento': 'payment',
    'personalità': 'personality',
    'realtà': 'reality',
    'sensazione': 'sensation',
    'servizio': 'service',
    'specializzazione': 'specialization',
    'stile': 'style',
    'sviluppo': 'development',
    'turismo': 'tourism',
    'vista': 'view, sight',
    'voglia': 'desire, wish',
    
    # People & professions
    'adolescente': 'adolescent, teenager',
    'esercito': 'army',
    'ladro': 'thief',
    'manager': 'manager',
    'operaio': 'worker',
    'pompiere': 'firefighter',
    'socio': 'partner, member',
    'soggetto': 'subject',
    'tabaccaio': 'tobacconist',
    
    # Adjectives
    'affatto': 'at all',
    'allora': 'then, so',
    'ammobiliato': 'furnished',
    'assurdo': 'absurd',
    'beato': 'blessed, lucky',
    'cin cin': 'cheers',
    'eccetera': 'etc., et cetera',
    'eh': 'eh',
    'ganzo': 'cool, great',
    'logico': 'logical',
    'magari': 'maybe, I wish',
    'morbido': 'soft',
    'netto': 'net, clear',
    'onesto': 'honest',
    'orizzontale': 'horizontal',
    'pedonale': 'pedestrian',
    'pessimista': 'pessimistic',
    'romantico': 'romantic',
    'spaventoso': 'frightening',
    'statale': 'state, public',
    'uffa': 'ugh, damn',
    
    # Verbs
    'abitare': 'to live, to inhabit',
    'abbassare': 'to lower',
    'accelerare': 'to accelerate',
    'accadere': 'to happen',
    'accogliere': 'to welcome',
    'affermare': 'to affirm, to state',
    'ammazzare': 'to kill',
    'appartenere': 'to belong',
    'assomigliare': 'to resemble',
    'augurare': 'to wish',
    'cavolo': 'cabbage, damn',
    'chissà': 'who knows',
    'cogliere': 'to pick, to catch',
    'compilare': 'to fill out',
    'concentrare': 'to concentrate',
    'denunciare': 'to report, to denounce',
    'difendere': 'to defend',
    'festeggiare': 'to celebrate',
    'frenare': 'to brake',
    'insistere': 'to insist',
    'investire': 'to invest, to run over',
    'liberare': 'to free, to release',
    'licenziare': 'to fire, to dismiss',
    'mettercela': 'to manage, to make it',
    'poiché': 'since, because',
    'regione': 'region',
    'riconoscere': 'to recognize',
    'riprendere': 'to resume, to take back',
    'sbucciare': 'to peel',
    'sdraiare': 'to lay down',
    'svegliarsi': 'to wake up',
    'tirare': 'to pull',
    'trovare': 'to find',
    'velocemente': 'quickly',
}

# Merge batch 9 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_9)

# Additional translations - Batch 10 (Final batch)
ADDITIONAL_TRANSLATIONS_10 = {
    # Simple nouns that were missed
    'bici': 'bike',
    'campo': 'field',
    'cartone': 'cardboard, cartoon',
    'caso': 'case',
    'cipolla': 'onion',
    'complemento': 'complement',
    'dialetto': 'dialect',
    'figura': 'figure',
    'fila': 'line, row',
    'fumo': 'smoke',
    'intorno': 'around',
    'pioggia': 'rain',
    'rumore': 'noise',
    'sorella': 'sister',
    'sorpresa': 'surprise',
    'verdura': 'vegetables',
    
    # Professions (with gender markers)
    'amministratore': 'administrator',
    'assassino': 'assassin',
    'attore': 'actor',
    'autore': 'author',
    'carabiniere': 'carabineer, police officer',
    'collaboratore': 'collaborator',
    'direttore': 'director',
    'dirigente': 'executive, manager',
    'dottore': 'doctor',
    'giocatore': 'player',
    'pittore': 'painter',
    'poeta': 'poet',
    'professore': 'professor, teacher',
    'regista': 'director (film/theater)',
    'responsabile': 'responsible, manager',
    'rettore': 'rector, chancellor',
    'scrittore': 'writer',
    'scultore': 'sculptor',
    'soldato': 'soldier',
    'studente': 'student',
    'vigile': 'traffic officer',
    
    # Common nouns
    'abilità': 'ability, skill',
    'agricoltura': 'agriculture',
    'ambiente': 'environment',
    'argomento': 'topic, argument',
    'asma': 'asthma',
    'aspetto': 'aspect, appearance',
    'attività': 'activity',
    'azione': 'action',
    'bellezza': 'beauty',
    'bilocale': 'two-room apartment',
    'bonifico': 'bank transfer',
    'brano': 'passage, piece (music)',
    'carabiniere': 'police officer',
    'certificato': 'certificate',
    'collocamento': 'placement, employment',
    'comportamento': 'behavior',
    'confronto': 'comparison',
    'considerazione': 'consideration',
    'consonante': 'consonant',
    'crisi': 'crisis',
    'decisione': 'decision',
    'democrazia': 'democracy',
    'Dio': 'God',
    'discorso': 'speech, discourse',
    'educazione': 'education',
    'epoca': 'era, epoch',
    'evidenza': 'evidence',
    'fede': 'faith',
    'frullatore': 'blender',
    'generazione': 'generation',
    'giardinaggio': 'gardening',
    'globalizzazione': 'globalization',
    'grammo': 'gram',
    'iscrizione': 'inscription, enrollment',
    'metodo': 'method',
    'nulla': 'nothing',
    'omicidio': 'homicide, murder',
    'onestà': 'honesty',
    'parentesi': 'parenthesis',
    'patto': 'pact, agreement',
    'politica': 'politics, policy',
    'povertà': 'poverty',
    'preoccupazione': 'worry, concern',
    'prestito': 'loan',
    'progetto': 'project',
    'residenza': 'residence',
    'ricevuta': 'receipt',
    'sentimento': 'feeling, sentiment',
    'sicurezza': 'safety, security',
    'significato': 'meaning',
    'sindacato': 'union, syndicate',
    'solitudine': 'solitude, loneliness',
    'spazio': 'space',
    'successo': 'success',
    'tassa': 'tax',
    'telegiornale': 'TV news',
    'testo': 'text',
    
    # Adjectives
    'abile': 'able, skilled',
    'altrettanto': 'equally, as much',
    'artificiale': 'artificial',
    'bollente': 'boiling',
    'disgustoso': 'disgusting',
    'inferiore': 'inferior, lower',
    'muto': 'mute, silent',
    'negativo': 'negative',
    'soddisfatto': 'satisfied',
    'storico': 'historical',
    'verticale': 'vertical',
    
    # Verbs
    'accomodarsi': 'to make oneself comfortable',
    'accusare': 'to accuse',
    'adorare': 'to adore',
    'allontanarsi': 'to move away',
    'aspettare': 'to wait, to expect',
    'assicurare': 'to insure, to assure',
    'augurare': 'to wish',
    'bagnare': 'to wet',
    'cavarsela': 'to manage, to get by',
    'chiamare': 'to call',
    'concentrare': 'to concentrate',
    'concludere': 'to conclude',
    'confrontare': 'to compare',
    'coniugare': 'to conjugate',
    'considerare': 'to consider',
    'contare': 'to count',
    'costringere': 'to force, to compel',
    'deludere': 'to disappoint',
    'deprimere': 'to depress',
    'discutere': 'to discuss',
    'ferire': 'to injure',
    'fermare': 'to stop',
    'figurarsi': 'to imagine',
    'impegnare': 'to commit, to engage',
    'incontrare': 'to meet',
    'interrompere': 'to interrupt',
    'lavare': 'to wash',
    'mantenere': 'to maintain',
    'mettere': 'to put',
    'muovere': 'to move',
    'occupare': 'to occupy',
    'piegare': 'to fold',
    'riferire': 'to report, to refer',
    'rimettersi': 'to recover, to start again',
    'riposare': 'to rest',
    'riprendere': 'to resume',
    'rispettare': 'to respect',
    'rompere': 'to break',
    'sconfiggere': 'to defeat',
    'sdraiare': 'to lay down',
    'sentire': 'to hear, to feel',
    'separare': 'to separate',
    'spiegare': 'to explain',
    'sposare': 'to marry',
    'stendere': 'to spread, to hang',
    'svegliare': 'to wake up',
    'trovare': 'to find',
    'vedere': 'to see',
    
    # Conjunctions & adverbs
    'benché': 'although',
    'contemporaneamente': 'simultaneously',
    'cordialmente': 'cordially',
    'sebbene': 'although',
}

# Merge batch 10 into main dictionary
TRANSLATIONS.update(ADDITIONAL_TRANSLATIONS_10)
