#!/usr/bin/env python3
"""
Translate Italian vocabulary entries that have 'Translation needed' as their English value.
This script provides English translations for CEFR vocabulary (A1, A2, B1, B2).
"""

import sqlite3
import json
from pathlib import Path

# Database path
DB_PATH = Path(__file__).parent.parent / 'data' / 'curriculum.db'

# Italian to English translations dictionary
# Organized by word type for clarity
TRANSLATIONS = {
    # Common words and prepositions
    'a': 'to, at',
    'di': 'of, from',
    'in': 'in, to',
    'da': 'from, by, since',
    'con': 'with',
    'su': 'on, about',
    'per': 'for, through',
    'tra': 'between, among',
    'fra': 'between, among',

    # Verbs (infinitive forms)
    'amare': 'to love',
    'aprire': 'to open',
    'arrivare': 'to arrive',
    'ascoltare': 'to listen',
    'aspettare': 'to wait',
    'avere': 'to have',
    'bastare': 'to be enough',
    'bere': 'to drink',
    'cadere': 'to fall',
    'cambiare': 'to change',
    'camminare': 'to walk',
    'cantare': 'to sing',
    'capire': 'to understand',
    'cercare': 'to look for, to search',
    'chiamare': 'to call',
    'chiudere': 'to close',
    'cominciare': 'to begin',
    'comprare': 'to buy',
    'conoscere': 'to know (a person/place)',
    'correre': 'to run',
    'costare': 'to cost',
    'credere': 'to believe',
    'cucinare': 'to cook',
    'dare': 'to give',
    'decidere': 'to decide',
    'dimenticare': 'to forget',
    'dire': 'to say, to tell',
    'diventare': 'to become',
    'domandare': 'to ask',
    'dormire': 'to sleep',
    'dovere': 'to have to, must',
    'entrare': 'to enter',
    'essere': 'to be',
    'fare': 'to do, to make',
    'fermare': 'to stop',
    'finire': 'to finish',
    'giocare': 'to play',
    'guardare': 'to watch, to look at',
    'guidare': 'to drive',
    'imparare': 'to learn',
    'incontrare': 'to meet',
    'insegnare': 'to teach',
    'lavorare': 'to work',
    'leggere': 'to read',
    'mandare': 'to send',
    'mangiare': 'to eat',
    'mettere': 'to put',
    'morire': 'to die',
    'mostrare': 'to show',
    'nascere': 'to be born',
    'offrire': 'to offer',
    'pagare': 'to pay',
    'parlare': 'to speak',
    'partire': 'to leave, to depart',
    'passare': 'to pass, to spend (time)',
    'pensare': 'to think',
    'perdere': 'to lose',
    'piacere': 'to please, to like',
    'piangere': 'to cry',
    'portare': 'to bring, to carry, to wear',
    'potere': 'to be able to, can',
    'prendere': 'to take',
    'preferire': 'to prefer',
    'preparare': 'to prepare',
    'presentare': 'to present, to introduce',
    'provare': 'to try',
    'pulire': 'to clean',
    'restare': 'to stay, to remain',
    'ricevere': 'to receive',
    'ricordare': 'to remember',
    'ridere': 'to laugh',
    'rimanere': 'to remain, to stay',
    'ripetere': 'to repeat',
    'riposare': 'to rest',
    'rispondere': 'to answer',
    'ritornare': 'to return',
    'rompere': 'to break',
    'salire': 'to go up, to climb',
    'salutare': 'to greet',
    'sapere': 'to know (a fact)',
    'sbagliare': 'to make a mistake',
    'scendere': 'to go down, to get off',
    'scegliere': 'to choose',
    'scrivere': 'to write',
    'scusare': 'to excuse',
    'seguire': 'to follow',
    'sembrare': 'to seem',
    'sentire': 'to hear, to feel',
    'servire': 'to serve',
    'smettere': 'to stop, to quit',
    'spedire': 'to send, to mail',
    'spendere': 'to spend (money)',
    'sperare': 'to hope',
    'spiegare': 'to explain',
    'stare': 'to stay, to be',
    'studiare': 'to study',
    'suonare': 'to play (instrument), to ring',
    'svegliare': 'to wake up',
    'telefonare': 'to phone',
    'tenere': 'to hold, to keep',
    'tornare': 'to return',
    'trovare': 'to find',
    'uscire': 'to go out',
    'vedere': 'to see',
    'vendere': 'to sell',
    'venire': 'to come',
    'vestire': 'to dress',
    'viaggiare': 'to travel',
    'vincere': 'to win',
    'visitare': 'to visit',
    'vivere': 'to live',
    'volere': 'to want',

    # Nouns
    'aceto': 'vinegar',
    'aereo': 'airplane',
    'affetto': 'affection',
    'agenzia': 'agency',
    'albero': 'tree',
    'alfabeto': 'alphabet',
    'ambasciata': 'embassy',
    'amico': 'friend',
    'amore': 'love',
    'animale': 'animal',
    'appartamento': 'apartment',
    'appuntamento': 'appointment',
    'arte': 'art',
    'autobus': 'bus',
    'automobile': 'car',
    'autunno': 'autumn, fall',
    'avvocato': 'lawyer',
    'bagno': 'bathroom',
    'bambino': 'child',
    'banca': 'bank',
    'bar': 'bar, café',
    'bicicletta': 'bicycle',
    'biglietto': 'ticket',
    'borsa': 'bag, purse',
    'bottiglia': 'bottle',
    'braccio': 'arm',
    'caldo': 'heat, warmth',
    'camera': 'room',
    'cameriere': 'waiter',
    'camicia': 'shirt',
    'campagna': 'countryside',
    'cane': 'dog',
    'canzone': 'song',
    'cappello': 'hat',
    'cappotto': 'coat',
    'carne': 'meat',
    'carta': 'paper',
    'casa': 'house, home',
    'cassiere': 'cashier',
    'centro': 'center',
    'ciao': 'hello, goodbye',
    'cielo': 'sky',
    'cinema': 'cinema, movie theater',
    'cintura': 'belt',
    'città': 'city',
    'classe': 'class',
    'cliente': 'client, customer',
    'colazione': 'breakfast',
    'collega': 'colleague',
    'collo': 'neck',
    'colore': 'color',
    'coltello': 'knife',
    'compleanno': 'birthday',
    'computer': 'computer',
    'conoscenza': 'knowledge, acquaintance',
    'consiglio': 'advice',
    'conto': 'bill, account',
    'conversazione': 'conversation',
    'coperta': 'blanket',
    'corpo': 'body',
    'corridoio': 'corridor, hallway',
    'corso': 'course',
    'cortile': 'courtyard',
    'cosa': 'thing',
    'costume': 'costume, swimsuit',
    'cotone': 'cotton',
    'cravatta': 'tie',
    'cucchiaio': 'spoon',
    'cucina': 'kitchen',
    'cugino': 'cousin',
    'cuore': 'heart',
    'dente': 'tooth',
    'denaro': 'money',
    'destra': 'right',
    'dito': 'finger',
    'documento': 'document',
    'dolce': 'dessert, sweet',
    'domanda': 'question',
    'donna': 'woman',
    'dottore': 'doctor',
    'dubbio': 'doubt',
    'edificio': 'building',
    'entrata': 'entrance',
    'errore': 'error, mistake',
    'esempio': 'example',
    'esperienza': 'experience',
    'estate': 'summer',
    'età': 'age',
    'euro': 'euro',
    'fabbrica': 'factory',
    'faccia': 'face',
    'fame': 'hunger',
    'famiglia': 'family',
    'farmacia': 'pharmacy',
    'favore': 'favor',
    'felicità': 'happiness',
    'fermata': 'stop (bus/tram)',
    'festa': 'party, holiday',
    'figlia': 'daughter',
    'figlio': 'son',
    'film': 'movie, film',
    'fine': 'end',
    'finestra': 'window',
    'fiore': 'flower',
    'firma': 'signature',
    'foglia': 'leaf',
    'foglio': 'sheet (of paper)',
    'fontana': 'fountain',
    'forchetta': 'fork',
    'formaggio': 'cheese',
    'forno': 'oven',
    'foto': 'photo',
    'fotografia': 'photograph',
    'francese': 'French',
    'fratello': 'brother',
    'freddo': 'cold',
    'fretta': 'hurry',
    'frigorifero': 'refrigerator',
    'frutta': 'fruit',
    'fuoco': 'fire',
    'gabinetto': 'toilet',
    'gamba': 'leg',
    'gatto': 'cat',
    'gelato': 'ice cream',
    'gente': 'people',
    'genitore': 'parent',
    'giacca': 'jacket',
    'giardino': 'garden',
    'ginocchio': 'knee',
    'giornale': 'newspaper',
    'giornata': 'day (duration)',
    'giorno': 'day',
    'giovane': 'young person',
    'gioventù': 'youth',
    'gita': 'trip, excursion',
    'gonna': 'skirt',
    'governo': 'government',
    'gradino': 'step',
    'grado': 'degree',
    'grido': 'shout, cry',
    'gruppo': 'group',
    'guanto': 'glove',
    'guerra': 'war',
    'gusto': 'taste',
    'idea': 'idea',
    'impiegato': 'employee, clerk',
    'impresa': 'enterprise, company',
    'incidente': 'accident',
    'incontro': 'meeting, encounter',
    'indirizzo': 'address',
    'infanzia': 'childhood',
    'infermiere': 'nurse',
    'informazione': 'information',
    'ingegnere': 'engineer',
    'inglese': 'English',
    'ingresso': 'entrance',
    'insalata': 'salad',
    'insegnante': 'teacher',
    'interesse': 'interest',
    'interno': 'interior',
    'inverno': 'winter',
    'invito': 'invitation',
    'isola': 'island',
    'italiano': 'Italian',
    'lago': 'lake',
    'lampada': 'lamp',
    'lana': 'wool',
    'latte': 'milk',
    'lato': 'side',
    'lavoro': 'work, job',
    'legge': 'law',
    'legno': 'wood',
    'lettera': 'letter',
    'letto': 'bed',
    'lettura': 'reading',
    'lezione': 'lesson',
    'libertà': 'freedom',
    'libreria': 'bookstore, bookshelf',
    'libro': 'book',
    'lì': 'there',
    'lingua': 'language, tongue',
    'lino': 'linen',
    'lira': 'lira (currency)',
    'lista': 'list',
    'locale': 'room, place',
    'luna': 'moon',
    'lunedì': 'Monday',
    'luogo': 'place',
    'luce': 'light',
    'macchina': 'car, machine',
    'madre': 'mother',
    'maestra': 'elementary teacher',
    'magazzino': 'warehouse, department store',
    'maggio': 'May',
    'maglietta': 'T-shirt',
    'maglione': 'sweater',
    'male': 'evil, pain',
    'mamma': 'mom',
    'mancanza': 'lack',
    'mano': 'hand',
    'manzo': 'beef',
    'mare': 'sea',
    'marito': 'husband',
    'martedì': 'Tuesday',
    'marzo': 'March',
    'materiale': 'material',
    'materia': 'subject, matter',
    'matita': 'pencil',
    'matrimonio': 'marriage, wedding',
    'mattina': 'morning',
    'medico': 'doctor',
    'mela': 'apple',
    'memoria': 'memory',
    'meno': 'less',
    'mensa': 'cafeteria',
    'mente': 'mind',
    'menù': 'menu',
    'mercato': 'market',
    'mercoledì': 'Wednesday',
    'mese': 'month',
    'mestiere': 'trade, occupation',
    'metà': 'half',
    'metro': 'meter, subway',
    'mezzanotte': 'midnight',
    'mezzo': 'means, half',
    'mezzogiorno': 'noon, midday',
    'miglio': 'mile',
    'minestra': 'soup',
    'minuto': 'minute',
    'misura': 'measure, size',
    'mobile': 'piece of furniture',
    'moda': 'fashion',
    'modello': 'model',
    'modo': 'way, manner',
    'moglie': 'wife',
    'momento': 'moment',
    'mondo': 'world',
    'montagna': 'mountain',
    'monumento': 'monument',
    'morte': 'death',
    'mostra': 'exhibition',
    'motivo': 'reason, motive',
    'moto': 'motorcycle',
    'motore': 'motor, engine',
    'movimento': 'movement',
    'mucca': 'cow',
    'muro': 'wall',
    'museo': 'museum',
    'musica': 'music',
    'nascita': 'birth',
    'naso': 'nose',
    'natura': 'nature',
    'nave': 'ship',
    'nazione': 'nation',
    'nebbia': 'fog',
    'negozio': 'shop, store',
    'nemico': 'enemy',
    'nero': 'black',
    'neve': 'snow',
    'nido': 'nest',
    'nipote': 'nephew, niece, grandchild',
    'nome': 'name',
    'nonno': 'grandfather',
    'nord': 'north',
    'notizia': 'news',
    'notte': 'night',
    'novità': 'novelty, news',
    'nozze': 'wedding',
    'numero': 'number',
    'nuora': 'daughter-in-law',
    'nuoto': 'swimming',
    'nuvola': 'cloud',

    # Adverbs
    'adesso': 'now',
    'ancora': 'still, yet, again',
    'anzi': 'on the contrary, rather',
    'appena': 'just, barely',
    'appunto': 'exactly, precisely',
    'assai': 'very much, a lot',
    'attraverso': 'through, across',
    'avanti': 'forward, ahead',
    'bene': 'well',
    'certamente': 'certainly',
    'certo': 'certainly',
    'circa': 'about, approximately',
    'come': 'how, as, like',
    'completamente': 'completely',
    'comunque': 'however, anyway',
    'contro': 'against',
    'così': 'so, thus',
    'davanti': 'in front',
    'davvero': 'really',
    'dentro': 'inside',
    'dietro': 'behind',
    'direttamente': 'directly',
    'dopo': 'after, later',
    'dove': 'where',
    'dovunque': 'wherever',
    'dunque': 'therefore, so',
    'durante': 'during',
    'ecco': 'here is, there is',
    'esattamente': 'exactly',
    'facilmente': 'easily',
    'finalmente': 'finally',
    'fino': 'until, up to',
    'forse': 'maybe, perhaps',
    'forte': 'strongly, loudly',
    'fuori': 'outside',
    'generalmente': 'generally',
    'già': 'already',
    'giù': 'down',
    'insieme': 'together',
    'invece': 'instead',
    'là': 'there',
    'laggiù': 'down there',
    'lassù': 'up there',
    'lontano': 'far',
    'lì': 'there',
    'male': 'badly',
    'mai': 'never, ever',
    'meglio': 'better',
    'mentre': 'while',
    'molto': 'very, much',
    'nemmeno': 'not even',
    'neanche': 'not even',
    'neppure': 'not even',
    'niente': 'nothing',
    'normalmente': 'normally',
    'oggi': 'today',
    'ogni': 'every',
    'ognuno': 'everyone',
    'oltre': 'beyond, besides',
    'oppure': 'or',
    'ora': 'now',
    'ormai': 'by now',
    'ovunque': 'everywhere',
    'parecchio': 'quite a lot',
    'peggio': 'worse',
    'per esempio': 'for example',
    'perché': 'why, because',
    'perciò': 'therefore',
    'perfettamente': 'perfectly',
    'perfino': 'even',
    'però': 'however, but',
    'personalmente': 'personally',
    'più': 'more',
    'piuttosto': 'rather',
    'poco': 'little, not much',
    'poi': 'then, later',
    'presto': 'soon, early',
    'prima': 'before, first',
    'probabilmente': 'probably',
    'proprio': 'really, exactly',
    'purtroppo': 'unfortunately',
    'qua': 'here',
    'qualche': 'some',
    'qualcosa': 'something',
    'qualcuno': 'someone',
    'quando': 'when',
    'quanto': 'how much',
    'quasi': 'almost',
    'quindi': 'therefore, so',
    'rapidamente': 'rapidly',
    'raramente': 'rarely',
    'recentemente': 'recently',
    'sempre': 'always',
    'semplice': 'simple',
    'semplicemente': 'simply',
    'senza': 'without',
    'sicuramente': 'surely, certainly',
    'solamente': 'only',
    'solo': 'only, alone',
    'soprattutto': 'above all, especially',
    'sopra': 'above, on',
    'sotto': 'under, below',
    'specialmente': 'especially',
    'spesso': 'often',
    'stamattina': 'this morning',
    'stasera': 'this evening, tonight',
    'stamani': 'this morning',
    'stanotte': 'tonight, last night',
    'subito': 'immediately',
    'su': 'up',
    'tardi': 'late',
    'tanto': 'so much',
    'troppo': 'too much',
    'tuttavia': 'however',
    'tutto': 'all, everything',
    'ugualmente': 'equally',
    'ultimamente': 'lately',
    'veramente': 'really, truly',
    'verso': 'toward',
    'via': 'away',
    'vicino': 'near, close',
    'volentieri': 'willingly, gladly',

    # Adjectives
    'alto': 'tall, high',
    'altro': 'other',
    'ampio': 'wide, ample',
    'antico': 'ancient, old',
    'aperto': 'open',
    'azzurro': 'blue, azure',
    'basso': 'low, short',
    'bello': 'beautiful',
    'bianco': 'white',
    'blu': 'blue',
    'bravo': 'good, clever',
    'breve': 'brief, short',
    'brutto': 'ugly',
    'buono': 'good',
    'caldo': 'hot, warm',
    'calmo': 'calm',
    'caro': 'dear, expensive',
    'cattivo': 'bad, evil',
    'centrale': 'central',
    'certo': 'certain',
    'chiaro': 'clear, light',
    'chiuso': 'closed',
    'completo': 'complete',
    'comune': 'common',
    'contento': 'happy, content',
    'corto': 'short',
    'debole': 'weak',
    'destro': 'right',
    'difficile': 'difficult',
    'diretto': 'direct',
    'diverso': 'different',
    'dolce': 'sweet',
    'duro': 'hard',
    'economico': 'economic, cheap',
    'enorme': 'enormous',
    'estero': 'foreign',
    'facile': 'easy',
    'falso': 'false',
    'famoso': 'famous',
    'felice': 'happy',
    'fermo': 'still, stationary',
    'forte': 'strong',
    'fresco': 'fresh, cool',
    'freddo': 'cold',
    'gentile': 'kind, polite',
    'giovane': 'young',
    'giusto': 'right, correct',
    'grande': 'big, large, great',
    'grasso': 'fat',
    'grave': 'serious, grave',
    'grigio': 'grey',
    'grosso': 'big, thick',
    'importante': 'important',
    'impossibile': 'impossible',
    'intero': 'entire, whole',
    'interessante': 'interesting',
    'internazionale': 'international',
    'italiano': 'Italian',
    'largo': 'wide',
    'leggero': 'light (weight)',
    'lento': 'slow',
    'libero': 'free',
    'lungo': 'long',
    'maggiore': 'greater, older',
    'magro': 'thin, lean',
    'malato': 'sick, ill',
    'marito': 'married',
    'maturo': 'mature, ripe',
    'medio': 'average, medium',
    'migliore': 'better, best',
    'minore': 'smaller, younger',
    'moderno': 'modern',
    'molle': 'soft',
    'morto': 'dead',
    'nazionale': 'national',
    'naturale': 'natural',
    'necessario': 'necessary',
    'nero': 'black',
    'nobile': 'noble',
    'normale': 'normal',
    'notevole': 'notable, remarkable',
    'nuovo': 'new',
    'numeroso': 'numerous',
    'occidentale': 'western',
    'occupato': 'busy, occupied',
    'opportuno': 'opportune, appropriate',
    'ordinario': 'ordinary',
    'orientale': 'eastern',
    'oscuro': 'dark, obscure',
    'ottimo': 'excellent',
    'ovvio': 'obvious',
    'pari': 'equal, even',
    'particolare': 'particular',
    'passato': 'past',
    'paziente': 'patient',
    'peggiore': 'worse, worst',
    'perfetto': 'perfect',
    'pericoloso': 'dangerous',
    'personale': 'personal',
    'pesante': 'heavy',
    'piccolo': 'small',
    'pieno': 'full',
    'pigro': 'lazy',
    'politico': 'political',
    'popolato': 'populated',
    'popolare': 'popular',
    'possibile': 'possible',
    'povero': 'poor',
    'pratico': 'practical',
    'preciso': 'precise',
    'preferito': 'favorite',
    'presente': 'present',
    'presto': 'early, quick',
    'prezioso': 'precious',
    'primo': 'first',
    'principale': 'main, principal',
    'privato': 'private',
    'probabile': 'probable',
    'profondo': 'deep',
    'prossimo': 'next',
    'pubblico': 'public',
    'pulito': 'clean',
    'puro': 'pure',
    'quale': 'which',
    'qualsiasi': 'any, whatever',
    'qualunque': 'any, whatever',
    'quanto': 'how much',
    'quarto': 'fourth',
    'quello': 'that',
    'questo': 'this',
    'quieto': 'quiet',
    'quinto': 'fifth',
    'rapido': 'rapid, fast',
    'raro': 'rare',
    'recente': 'recent',
    'regionale': 'regional',
    'regolare': 'regular',
    'religioso': 'religious',
    'ricco': 'rich',
    'ridotto': 'reduced',
    'riservato': 'reserved',
    'romano': 'Roman',
    'rosso': 'red',
    'rotondo': 'round',
    'russo': 'Russian',
    'sacro': 'sacred',
    'salato': 'salty',
    'sano': 'healthy',
    'santo': 'saint, holy',
    'sbagliato': 'wrong, mistaken',
    'scarso': 'scarce',
    'scemo': 'stupid',
    'sciocco': 'foolish',
    'scomodo': 'uncomfortable',
    'sconosciuto': 'unknown',
    'scoperto': 'discovered, uncovered',
    'scorso': 'last, past',
    'scritto': 'written',
    'scuro': 'dark',
    'secco': 'dry',
    'secondo': 'second',
    'segreto': 'secret',
    'semplice': 'simple',
    'sensibile': 'sensitive',
    'serio': 'serious',
    'sereno': 'serene, clear',
    'severo': 'severe, strict',
    'sicuro': 'sure, safe',
    'significativo': 'significant',
    'simile': 'similar',
    'simpatico': 'nice, likeable',
    'sincero': 'sincere',
    'singolo': 'single',
    'sinistro': 'left',
    'sociale': 'social',
    'sodo': 'hard, firm',
    'solo': 'alone, only',
    'solito': 'usual',
    'sordo': 'deaf',
    'sorpreso': 'surprised',
    'sottile': 'thin, subtle',
    'spagnolo': 'Spanish',
    'speciale': 'special',
    'specifico': 'specific',
    'sporco': 'dirty',
    'stanco': 'tired',
    'strano': 'strange',
    'stretto': 'narrow, tight',
    'stupido': 'stupid',
    'successivo': 'successive, next',
    'sufficiente': 'sufficient',
    'superiore': 'superior, upper',
    'supremo': 'supreme',
    'sveglio': 'awake, alert',
    'tale': 'such',
    'tanto': 'so much',
    'tardo': 'late',
    'tedesco': 'German',
    'tenero': 'tender',
    'terribile': 'terrible',
    'terzo': 'third',
    'tipico': 'typical',
    'totale': 'total',
    'tranquillo': 'calm, quiet',
    'triste': 'sad',
    'troppo': 'too much',
    'ultimo': 'last',
    'uguale': 'equal',
    'unico': 'unique, only',
    'unito': 'united',
    'universale': 'universal',
    'umano': 'human',
    'umido': 'humid, damp',
    'urgente': 'urgent',
    'usato': 'used',
    'utile': 'useful',
    'vario': 'various',
    'vasto': 'vast',
    'vecchio': 'old',
    'veloce': 'fast',
    'vero': 'true',
    'verde': 'green',
    'vergine': 'virgin',
    'vicino': 'near',
    'vigile': 'vigilant',
    'vile': 'vile, cowardly',
    'vivo': 'alive, living',
    'vocale': 'vocal',
    'vuoto': 'empty',

    # Conjunctions
    'anche': 'also, too',
    'che': 'that, which, who',
    'dunque': 'therefore',
    'e': 'and',
    'ma': 'but',
    'mentre': 'while',
    'o': 'or',
    'oppure': 'or',
    'perché': 'because, why',
    'però': 'however, but',
    'quando': 'when',
    'quindi': 'therefore',
    'se': 'if',
    'sia': 'both, whether',

    # Interjections
    'aiuto': 'help',
    'arrivederci': 'goodbye',
    'attenzione': 'attention',
    'auguri': 'best wishes',
    'basta': 'enough',
    'bene': 'well, good',
    'bravo': 'well done',
    'buongiorno': 'good morning, hello',
    'buonasera': 'good evening',
    'buonanotte': 'good night',
    'ciao': 'hi, bye',
    'congratulazioni': 'congratulations',
    'ecco': 'here is',
    'grazie': 'thank you',
    'prego': 'you\'re welcome, please',
    'salve': 'hello',
    'scusa': 'sorry, excuse me',
    'scusi': 'excuse me (formal)',
    'sì': 'yes',
    'no': 'no',
    'va bene': 'okay',

    # Pronouns
    'chi': 'who',
    'ci': 'us, there',
    'io': 'I',
    'lei': 'she, you (formal)',
    'loro': 'they, them',
    'lui': 'he',
    'me': 'me',
    'mi': 'me, myself',
    'noi': 'we',
    'qualcuno': 'someone',
    'qualcosa': 'something',
    'se': 'oneself',
    'si': 'oneself, one',
    'te': 'you',
    'ti': 'you, yourself',
    'tu': 'you',
    'voi': 'you (plural)',
}


def translate_word(italian: str, word_type: str = None) -> str:
    """
    Translate an Italian word to English.
    Returns the translation if found, otherwise returns the original word.
    """
    # Clean the Italian word (remove articles)
    clean = italian.lower().strip()

    # Remove common articles
    for article in ['il ', 'lo ', 'la ', "l'", 'i ', 'gli ', 'le ', 'un ', 'uno ', 'una ', "un'"]:
        if clean.startswith(article):
            clean = clean[len(article):]
            break

    # Look up in dictionary
    if clean in TRANSLATIONS:
        return TRANSLATIONS[clean]

    # If not found, return indication that manual translation is needed
    return f"NEEDS_MANUAL: {italian}"


def main():
    """Main function to translate vocabulary."""
    print("Starting vocabulary translation...")
    print(f"Database: {DB_PATH}")

    # Connect to database
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Get all entries that need translation
    cursor.execute("""
        SELECT id, italian, word_type, level
        FROM vocabulary
        WHERE english = 'Translation needed'
        ORDER BY level, italian
    """)

    entries = cursor.fetchall()
    total = len(entries)
    print(f"\nFound {total} entries needing translation")

    # Track translations
    translated = 0
    needs_manual = 0
    manual_list = []

    # Translate each entry
    for entry_id, italian, word_type, level in entries:
        translation = translate_word(italian, word_type)

        if translation.startswith("NEEDS_MANUAL"):
            needs_manual += 1
            manual_list.append((entry_id, italian, word_type, level))
        else:
            # Update database
            cursor.execute("""
                UPDATE vocabulary
                SET english = ?
                WHERE id = ?
            """, (translation, entry_id))
            translated += 1

            if translated % 100 == 0:
                print(f"Progress: {translated}/{total} ({translated*100//total}%)")

    # Commit changes
    conn.commit()

    # Print summary
    print(f"\n{'='*60}")
    print(f"TRANSLATION SUMMARY")
    print(f"{'='*60}")
    print(f"Total entries processed: {total}")
    print(f"Successfully translated: {translated}")
    print(f"Needs manual translation: {needs_manual}")
    print(f"Success rate: {translated*100//total}%")

    # Save list of words needing manual translation
    if manual_list:
        output_file = Path(__file__).parent.parent / 'data' / 'needs_manual_translation.json'
        manual_data = [
            {'id': e[0], 'italian': e[1], 'word_type': e[2], 'level': e[3]}
            for e in manual_list
        ]
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(manual_data, f, indent=2, ensure_ascii=False)
        print(f"\nList of words needing manual translation saved to:")
        print(f"{output_file}")

    conn.close()
    print("\nTranslation complete!")


if __name__ == '__main__':
    main()
